/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Alphabetical_list_of_products(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Alphabetical_list_of_products_IR();
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = ' nKvTyPqpPm7OyutwmV43p9CQ9Cb7eZnGGbNkUtL';
	retObj.SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.QuantityPerUnit = 'iBYCTFvnfaFxfzYfHkHC';
	retObj.UnitPrice = 0.06008687161742643;
	retObj.UnitsInStock = -943;
	retObj.UnitsOnOrder = -16389;
	retObj.ReorderLevel = -15369;
	retObj.Discontinued = false;
	retObj.CategoryName = 'EztU94ApyNb1jmE';
	return retObj;
}
