/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_CustOrdersOrders(fillPrimaryKey = false) {
	var retObj = new Northwind_dbo_CustOrdersOrders_OM_IR();
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.OrderDate = '/Date(4/2/2015 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(4/15/2016 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(8/23/2015 12:00:00 AM)/';
	return retObj;
}
