/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Sales_Totals_by_Amount(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Sales_Totals_by_Amount_IR();
	retObj.SaleAmount = 0.31074952326707805;
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CompanyName = '0Ncx3zbwVZpbq0x1AjL0Mon1XgZcgxbY6z9 a3G8';
	retObj.ShippedDate = '/Date(8/25/2016 12:00:00 AM)/';
	return retObj;
}
