/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_ProductsAndCategories(fillPrimaryKey = false) {
	var retObj = new Northwind_dbo_ProductsAndCategories_OM_IR();
	retObj.Query1_Results_IR.ToList().push({});
	retObj.query1_Results_IR[0].ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].ProductName = 'gCsdTwJevm8DkcKO 4OFDrt0ziGI7VmZ3XxqiAtJ';
	retObj.query1_Results_IR[0].SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].QuantityPerUnit = 'BergCrwdraAYqlcAL1gy';
	retObj.query1_Results_IR[0].UnitPrice = 0.4800226742432461;
	retObj.query1_Results_IR[0].UnitsInStock = 22621;
	retObj.query1_Results_IR[0].UnitsOnOrder = -4049;
	retObj.query1_Results_IR[0].ReorderLevel = 26348;
	retObj.query1_Results_IR[0].Discontinued = true;
	retObj.Query2_Results_IR.ToList().push({});
	retObj.query2_Results_IR[0].CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query2_Results_IR[0].CategoryName = '6eECdCFmatqSpjL';
	retObj.query2_Results_IR[0].Description = 'RHPzD2b23LHJZW5IR0tF0IqDbmkVp7l1ytUlyPhV0huDgCYTSdpiHVZxILPVrkRHHpbSAxAL0s17Q3Y9Cq WDGhWFObvAahU0CTe';
	retObj.query2_Results_IR[0].Picture = new Int8Array([115,228,247,234,137,241,76,36,201,35,7,102,188,2,132,36,157,149,44,117,243,52,88,192,45,18,198,199,245,25,41,224,40,81,185,87,59,77,81,38,156,241,170,174,161,92,138,94,23,135,137,25,111,220,245,165,133,249,98,128,8,153,84,31,237,53,221,193,103,134,100,10,123,22,181,120,209,155,24,238,59,70,155,96,159,66,10,217,111,105,105,28,118,87,133,186,181,255,212,130]);
	return retObj;
}
