/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Quarterly_Orders(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Quarterly_Orders_IR();
	retObj.CustomerID = (fillPrimaryKey ? 'QaNTo' : null);
	retObj.CompanyName = 'U8JYMpo2vFt0nWt6FqJopoVRMxVGZvM5n1jV659b';
	retObj.City = ' e7NDLrGhu3XcsO';
	retObj.Country = ' AG oBi4Pdubt y';
	return retObj;
}
