/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Categories(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Categories_IR();
	retObj.CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CategoryName = 'dbRCrvWU9Me4FYI';
	retObj.Description = '4SiTSkFPq41liQq7CVqkKvgIquBudna5A4pK3iIu9tGy6fAH24G8iiFrdNzjVogMHD ZQnykaGUHKCBgLDONUEATBc1Y1MH20yPE';
	retObj.Picture = new Int8Array([146,111,84,41,31,107,6,117,187,140,218,195,48,221,4,183,83,232,44,183,192,117,126,38,26,78,119,200,149,228,129,20,171,21,253,85,53,207,182,228,72,60,248,97,196,25,109,135,169,33,53,234,149,123,11,155,243,231,15,63,88,205,56,19,143,123,132,134,159,34,195,30,169,6,54,40,15,165,139,2,40,134,76,186,146,110,203,149,53,99,10,142,214,220,185,131,222,111,93,212]);
	return retObj;
}
