/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Employees(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Employees_IR();
	retObj.EmployeeID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.LastName = 'NFHXW9Wfl3myaCArKZGI';
	retObj.FirstName = 'pb3Z4zPC k';
	retObj.Title = 'uMk86y0cyOAaUowzouDKiG5gpsytPF';
	retObj.TitleOfCourtesy = 'ZP8pnmofM03BUSGZXd2pEw4Vj';
	retObj.BirthDate = '/Date(5/25/2003 12:00:00 AM)/';
	retObj.HireDate = '/Date(5/26/2012 12:00:00 AM)/';
	retObj.Address = 'hUJKCr8frtM8eGTEfHYPm4s7qiigESI A9LTtEZ1YEZlrZRAecVhte6U1PaI';
	retObj.City = 'gR7SYsBDYcbUA K';
	retObj.Region = 'zW lkpS4dvoYkbB';
	retObj.PostalCode = '7QdgjdcS2Y';
	retObj.Country = 'YTf jwTksZY kzN';
	retObj.HomePhone = 'MSY15ZWgnp0n5tY4X3Eg TXC';
	retObj.Extension = 'wKNx';
	retObj.Photo = new Int8Array([105,35,224,124,0,166,96,68,13,122,207,8,15,9,167,174,227,216,234,192,148,238,66,167,250,23,97,35,90,42,187,5,51,128,78,184,43,147,217,75,37,200,59,216,68,234,238,162,185,48,30,254,156,197,242,58,83,225,228,89,134,107,39,54,181,90,163,7,235,192,32,42,98,177,208,26,255,162,175,58,200,252,226,202,161,14,94,83,135,198,128,64,171,97,147,138,85,59,64,196]);
	retObj.Notes = 'ajyxwwUSaYBFhiqD8y4 XC95tjv0mp KGHtuX0j041r2vK4 fNd H1XJH0HXhrEs mAJDbR1MO4nDmKv1uTZSVxOg0JZl75HiWxh';
	retObj.ReportsTo_IR = encrypt(1);
	retObj.PhotoPath = '8Fo8HZS5EWN6aea03yUBbHxQVTnaUS14TOOJn4FgbT7BCRPgUvshl9OYIpxvYNj6xeGG8rwaDunRBsGJLlUXRkCXxFP gBx7eJGnpsKPHSEQxkqDqIjMwWaGM2YBjfPpUr5N7KzrBqxIZLkyHjL Q8AAcoFAH5owDpYmOxNjJIqUaq72uBSJk2V5jQdK ew4s8aTQYPjToezLbgoet5SzJ4   kyGoLp8ueq9X9n4WyclWFQQzV0DKYpbhZpikf';
	// Foreign key entities
	retObj.FK_Employees_Employees_Ref_IR = getHydratedStaticNorthwind_dbo_Employees_IR();
	return retObj;
}
