/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Customer_and_Suppliers_by_City(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Customer_and_Suppliers_by_City_IR();
	retObj.City = 'ocrD29SfrcW99rm';
	retObj.CompanyName = 'XTK5pEAl4r3qtmD1PZ8b6PcecsRZDz2jl4dG86du';
	retObj.ContactName = 'ydtUra8FLQtrg1bKK5JF8aDDzXDiU5';
	retObj.Relationship = 'YvjEsbspa';
	return retObj;
}
