/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Customers(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Customers_IR();
	retObj.CustomerID = (fillPrimaryKey ? '9l4A7' : null);
	retObj.CompanyName = 'TdE TEzoQXCKm4V3RWmpzSGaSfXQLUVQ5ylyUjBy';
	retObj.ContactName = 'RQ PdbsD3g8zOwTOENpNxzOhWNOMwQ';
	retObj.ContactTitle = 'dti8NJi4EAMOjddaqkURkTflXPcEIG';
	retObj.Address = 'oAjyzfFw4DZ3dPl3C0ANGQF8aWY0F4EBUwcQn LDAj k2tgHwklnFDuWv rh';
	retObj.City = 'KfIIFQWM80ecy9p';
	retObj.Region = 'zlF4hWCgoqZdYJJ';
	retObj.PostalCode = 't0qHpipOz5';
	retObj.Country = 'kTnWnInkSvU0IY ';
	retObj.Phone = '7ft6qXyaWJwQgGLPSKp3h8sY';
	retObj.Fax = 'yYIdcksKzAgrTjZJRONNmN52';
	return retObj;
}
