/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Orders_Qry(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Orders_Qry_IR();
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CustomerID = (fillPrimaryKey ? 'xYBs0' : null);
	retObj.EmployeeID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.OrderDate = '/Date(6/23/2007 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(3/27/2020 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(4/16/1995 12:00:00 AM)/';
	retObj.ShipVia = 263555276;
	retObj.Freight = 0.5663324640198606;
	retObj.ShipName = '1dZvDYnCfBdA9gCASawm2fusfrjd67DFm31dyvKX';
	retObj.ShipAddress = 'JoGl64BqgIFrdIzoXWAu3sy6cJWZ4LIIyUm9rFZHxtCKoXzf1qTG Dp2v Ff';
	retObj.ShipCity = 'Bpe VsMvEh7JDmz';
	retObj.ShipRegion = 'lZ5zZnLQLbXykTJ';
	retObj.ShipPostalCode = 'FQpN7RL6PW';
	retObj.ShipCountry = 'Bh0Le i8h4Egbu7';
	retObj.CompanyName = 'HvwDunyYCuXJPMYqvInN8mNj7t9NZQ7Kw3oJzeal';
	retObj.Address = 'sQ8quyyycXbSNij8DrbzJEco7U3AvTzh7shPyYK1b1NWfIRWYg2d78LxReDX';
	retObj.City = 'UfrSLiLOGusufm9';
	retObj.Region = 'vxq 4okbJ3CtEMA';
	retObj.PostalCode = 'Pf5rmJh8LL';
	retObj.Country = 'W1z0PDpTO1J85wb';
	return retObj;
}
