/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Products_by_Category(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Products_by_Category_IR();
	retObj.CategoryName = 'xNvkqm72vsNK0gO';
	retObj.ProductName = '5NjEDr7NvDrZw1MXnnW upu3X12IhuXJ3u3X5GPl';
	retObj.QuantityPerUnit = 'MZZRZpaN6tnyEoAqPR40';
	retObj.UnitsInStock = 13904;
	retObj.Discontinued = false;
	return retObj;
}
