/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Summary_of_Sales_by_Quarter(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Summary_of_Sales_by_Quarter_IR();
	retObj.ShippedDate = '/Date(5/25/2020 12:00:00 AM)/';
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.Subtotal = 0.8455587822241762;
	return retObj;
}
