/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Suppliers(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Suppliers_IR();
	retObj.SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CompanyName = 'bCi4jCEibjpf8T2V1o1njOMiuMmt7vWfWBfpam4E';
	retObj.ContactName = '0ADetfNbdWWxaj2MNIG2lOQBInHbrj';
	retObj.ContactTitle = '7 qlWJ7MMG6esaBst6 PLZemaqLx1g';
	retObj.Address = 'aDo jPtNeDwYAdB9a1F2XUlDF7kUNqGgAj0CBMnIepIvOBTk2S4fNSH9y4Lh';
	retObj.City = '3aIA hqqOt miCa';
	retObj.Region = 'WE3dFN3CPupuW 9';
	retObj.PostalCode = 'zlsRoR2vlz';
	retObj.Country = 'o6qDtUNPrwOfZGU';
	retObj.Phone = 'qF9IuepRSOoRoyKTKoBE1p9P';
	retObj.Fax = 'pN04OOoqCyEUE3w5  RSiWbk';
	retObj.HomePage = 'lxExJtAhVTeCP5sTGMOLj4gU5Q1zkRmWvmIhyHphwCdIafpp tx3gBKIqR 1ox70 O1mbJn2cH0frQOFIUGDydnGAqwTu8MhVXXI';
	return retObj;
}
