/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Territories(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Territories_IR();
	retObj.TerritoryID = (fillPrimaryKey ? '2tXorKM0PHiUimFkLqeR' : null);
	retObj.TerritoryDescription = 'cga1ErSjKhxdzmpqaAVulmZ6mS7xJkw0IkRBBv8zVCn8442o2P';
	retObj.RegionID_IR = encrypt(1);
	// Foreign key entities
	retObj.FK_Territories_Region_Ref_IR = getHydratedStaticNorthwind_dbo_Region_IR();
	return retObj;
}
