/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_CustOrdersDetail(fillPrimaryKey = false) {
	var retObj = new Northwind_dbo_CustOrdersDetail_OM_IR();
	retObj.ProductName = 'yFiJaONwAcKNzDJ566tBSrSyGPlZrytE8IK2yyfg';
	retObj.UnitPrice = 0.2312795945118875;
	retObj.Quantity = -17159;
	retObj.Discount = -2017244480;
	retObj.ExtendedPrice = 0.0007402243031295885;
	return retObj;
}
