/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Orders(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Orders_IR();
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CustomerID = 'Ysg2 ';
	retObj.EmployeeID_IR = encrypt(1);
	retObj.OrderDate = '/Date(1/11/2010 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(9/11/2012 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(6/3/2007 12:00:00 AM)/';
	retObj.ShipVia_IR = encrypt(1);
	retObj.Freight = 0.5699887701747025;
	retObj.ShipName = 'OvGKB9rkyNVgo3QJRJO9wso3X1sALj9H6Mj2XS4T';
	retObj.ShipAddress = 'bMylSS9KF2f8IwcSqLs6BNbWjZLewMR7OHdEP84kauj5bjyOuum69T6LGuvw';
	retObj.ShipCity = 'EyedgZvDGrAlTrm';
	retObj.ShipRegion = 'E7TEEXQ4knHHO i';
	retObj.ShipPostalCode = 'hzxQZF89xU';
	retObj.ShipCountry = 'it7oJ9i3jkJsZRh';
	// Foreign key entities
	retObj.FK_Orders_Customers_Ref_IR = getHydratedStaticNorthwind_dbo_Customers_IR();
	retObj.FK_Orders_Employees_Ref_IR = getHydratedStaticNorthwind_dbo_Employees_IR();
	retObj.FK_Orders_Shippers_Ref_IR = getHydratedStaticNorthwind_dbo_Shippers_IR();
	return retObj;
}
