/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_CustOrderHist(fillPrimaryKey = false) {
	var retObj = new Northwind_dbo_CustOrderHist_OM_IR();
	retObj.ProductName = '6lcBNWIhN3MTmdAfj3xsSdht8uB6nV5y4j5qLioB';
	retObj.Total = -1577733770;
	return retObj;
}
