/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Invoices(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Invoices_IR();
	retObj.ShipName = 'qQPxUD1Uy5usYD5eYRqqkyaCCuMu7PS21SoQOwxD';
	retObj.ShipAddress = 'emcxxnQeKXNXJ7lvhQ6Z2Wn8XB7Gu2S1XJot5LK9pnOh73zJ1lWCn2NIp63y';
	retObj.ShipCity = 'rWjxNMj1FCswKdw';
	retObj.ShipRegion = 'SvqEHlt5VkbpbiZ';
	retObj.ShipPostalCode = 'e00YHVduqq';
	retObj.ShipCountry = 'wAM6Ibe0u6 xnSE';
	retObj.CustomerID = (fillPrimaryKey ? 'UcNFx' : null);
	retObj.CustomerName = 'lyM74oxPDMp2fnTMfAgTh7Z2snG2ERdD7spf7sZn';
	retObj.Address = 'RCYlgGuUR7Wl2YWLz1WO9wOdWhEo4my5GABqUxbf0W96BjdZi3xRvrQf0lm3';
	retObj.City = 'dM8EY1sKn0A5zKH';
	retObj.Region = 'Pq84OnSgks1nxcl';
	retObj.PostalCode = 'x5LmJ 3Ets';
	retObj.Country = 'qKTrAZ5fP80naQe';
	retObj.Salesperson = 'dJJdecB9oTOp9wR W5U3K0vdtmlBKTa';
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.OrderDate = '/Date(11/11/1996 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(5/15/2013 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(7/15/2012 12:00:00 AM)/';
	retObj.ShipperName = 'QKDymaJ4EXCnTxIixzyAxN7o8bvM55pqw7kIvxEu';
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = 'JiAaqQTgbDKBXMyNuurVSGZE3MhNLdn BxTM2Uh ';
	retObj.UnitPrice = 0.06178012257255294;
	retObj.Quantity = -6830;
	retObj.Discount = 0.48680568;
	retObj.ExtendedPrice = 0.7088532003750941;
	retObj.Freight = 0.6102781530850651;
	return retObj;
}
