/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class XE_HR_HydratedStaticIndirectReferenceTransformerModels : XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public XE_HR_EMP_DETAILS_VIEW_IR GetHydratedStaticXE_HR_EMP_DETAILS_VIEW_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_EMP_DETAILS_VIEW_IR();
		retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.JOB_ID = (fillPrimaryKey ? "yi4XZGBtQd" : String.Empty);
		retObj.MANAGER_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.DEPARTMENT_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.LOCATION_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.COUNTRY_ID = (fillPrimaryKey ? "xu" : String.Empty);
		retObj.FIRST_NAME = "fkIej4PNvQPamd7S2OS9";
		retObj.LAST_NAME = "zyBboMy2ftdNWiyisAWm3GXpZ";
		retObj.SALARY = (0.596654380645425M);
		retObj.COMMISSION_PCT = (0.9409056702298607M);
		retObj.DEPARTMENT_NAME = "M477 oPcCZ1isDY7bHImOLvk9gxll8";
		retObj.JOB_TITLE = "YsL33lr4AHyR1NlPwH aI51CdLTja6BpDgd";
		retObj.CITY = "cmNKw1qyF3gGTSWmq ZzCD2z mq5GV";
		retObj.STATE_PROVINCE = "aPySxPVH9dBPVV3XPAKblQRnX";
		retObj.COUNTRY_NAME = "wvUL7O3ph03vLNl7vhPY7 FUOPkrcDpSlhsXja5l";
		retObj.REGION_NAME = "26wAojtrWycC2r Ev9Qzk94VL";
		return retObj;
	}
}
