/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class XE_HR_HydratedStaticIndirectReferenceTransformerModels : XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public XE_HR_PACKAGE1_OPEN_ONE_CURSOR_OM_IR GetHydratedStaticXE_HR_PACKAGE1_OPEN_ONE_CURSOR_OM_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_PACKAGE1_OPEN_ONE_CURSOR_OM_IR();
		retObj.Query1_Results_IR!.ToList().Add(new XE_HR_PACKAGE1_OPEN_ONE_CURSOR_OM_Query1_IR());
		retObj.Query1_Results_IR!.First()!.EMPLOYEE_ID_IR = _encryptionDecryptionService!.EncDecimal(Convert.ToDecimal(1));
		retObj.Query1_Results_IR!.First()!.JOB_ID = "m8D8S5Bj1O";
		retObj.Query1_Results_IR!.First()!.MANAGER_ID_IR = _encryptionDecryptionService!.EncDecimalNullable(Convert.ToDecimal(1));
		retObj.Query1_Results_IR!.First()!.DEPARTMENT_ID_IR = _encryptionDecryptionService!.EncDecimalNullable(Convert.ToDecimal(1));
		retObj.Query1_Results_IR!.First()!.LOCATION_ID_IR = _encryptionDecryptionService!.EncDecimalNullable(Convert.ToDecimal(1));
		retObj.Query1_Results_IR!.First()!.COUNTRY_ID = "cT";
		retObj.Query1_Results_IR!.First()!.FIRST_NAME = "vgl1Xk2cVpGn0ALEbDS1";
		retObj.Query1_Results_IR!.First()!.LAST_NAME = "8y6seeAPXiBrisaEmGtS3zfQ1";
		retObj.Query1_Results_IR!.First()!.SALARY = (0.4506079216367682M);
		retObj.Query1_Results_IR!.First()!.COMMISSION_PCT = (0.5367894873739927M);
		retObj.Query1_Results_IR!.First()!.DEPARTMENT_NAME = "oQbncpsTnmpHsp0EQSgHlytdwMkiJP";
		retObj.Query1_Results_IR!.First()!.JOB_TITLE = "dYxpjrW0j2r1Bft etgByfrgkIWPeOuacL5";
		retObj.Query1_Results_IR!.First()!.CITY = "ryn1JsULoDG4b2Fh0wyT9dmllX3QjR";
		retObj.Query1_Results_IR!.First()!.STATE_PROVINCE = "HV6J9B0GqTQoI3tPtHmz oW m";
		retObj.Query1_Results_IR!.First()!.COUNTRY_NAME = "NMAgKYL1WN5UJklSzLQlEoQxidklNs5n9solw7Wd";
		retObj.Query1_Results_IR!.First()!.REGION_NAME = "GUlrSv0hBIaIchvaZSgf 7fm9";
		return retObj;
	}
}
