/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class XE_HR_HydratedStaticIndirectReferenceTransformerModels : XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_IR GetHydratedStaticXE_HR_PACKAGE1_PARAMOUTCURSORS_OM_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_IR();
		// Output parameters
		retObj.CONVERTED_TO_VARCHAR2 = "KT3AkjQVZRL RcFm7qVmKBRC3Em3N6MyUoGfnhROPA48MWm55UmvOdlOqcGumrlseHP5CSTWJczPor4eZViG3MEJ9h7aDlX1WSGK";
		retObj.Query1_Results_IR!.ToList().Add(new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_Query1_IR());
		retObj.Query1_Results_IR!.First()!.EMPLOYEE_ID_IR = _encryptionDecryptionService!.EncDecimal(Convert.ToDecimal(1));
		retObj.Query1_Results_IR!.First()!.START_DATE = "w5rLUpF";
		retObj.Query1_Results_IR!.First()!.END_DATE = "XLgODhX";
		retObj.Query1_Results_IR!.First()!.JOB_ID = "tZYUz1oYXC";
		retObj.Query1_Results_IR!.First()!.DEPARTMENT_ID_IR = _encryptionDecryptionService!.EncDecimalNullable(Convert.ToDecimal(1));
		retObj.Query2_Results_IR!.ToList().Add(new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_Query2_IR());
		retObj.Query2_Results_IR!.First()!.DEPARTMENT_ID_IR = _encryptionDecryptionService!.EncDecimal(Convert.ToDecimal(1));
		retObj.Query2_Results_IR!.First()!.DEPARTMENT_NAME = "cJWg9V73VATlSp28x3dAgER0TT2Gwp";
		retObj.Query2_Results_IR!.First()!.MANAGER_ID_IR = _encryptionDecryptionService!.EncDecimalNullable(Convert.ToDecimal(1));
		retObj.Query2_Results_IR!.First()!.LOCATION_ID_IR = _encryptionDecryptionService!.EncDecimalNullable(Convert.ToDecimal(1));
		return retObj;
	}
}
