/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Products_by_Category GetHydratedStaticNorthwind_dbo_Products_by_Category(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Products_by_Category();
		retObj.CategoryName = "B85F0dPS4WtztIG";
		retObj.ProductName = "Nx8EOS5mZoFcplSOPKevv2KPEkvjQBYPIiDwwWS4";
		retObj.QuantityPerUnit = "k LygIAuQsNBsjUn eQI";
		retObj.UnitsInStock = (-17584);
		retObj.Discontinued = (true);
		return retObj;
	}
}
