/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Products_Above_Average_Price GetHydratedStaticNorthwind_dbo_Products_Above_Average_Price(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Products_Above_Average_Price();
		retObj.ProductName = "GWBrrViNrOS6wpnZ38N5wNaP3hqYNEsaV20GX0X4";
		retObj.UnitPrice = (0.03539534324178195M);
		return retObj;
	}
}
