/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Employees GetHydratedStaticNorthwind_dbo_Employees(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Employees();
		retObj.EmployeeID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.LastName = "wARFgIwEi4LFytT7MC3n";
		retObj.FirstName = "obAbfLeGDR";
		retObj.Title = "aXWzlIBTz0F2WoQjrQXtzquHeGGKWs";
		retObj.TitleOfCourtesy = "CvnJ3K33VlTpEgO8dU8qVo6EQ";
		retObj.BirthDate = DateTime.Parse("12/5/2002 12:00:00 AM");
		retObj.HireDate = DateTime.Parse("7/9/2007 12:00:00 AM");
		retObj.Address = "sw7y0kB37bctkamGNY VoSTNuX1tTdBfLCOqJVaf9bXcbWQa2mpfWj8lOBvp";
		retObj.City = "2IxZQs7IieBep3B";
		retObj.Region = "PqBcLCI6DI6vFMM";
		retObj.PostalCode = "zuE21Ap36p";
		retObj.Country = "G7vf7m40UDv4wM8";
		retObj.HomePhone = "JnxXRnUJ7BUZZIhojwR1YQOl";
		retObj.Extension = "N3aW";
		retObj.Photo = new Byte[] { 164, 254, 131, 190, 124, 101, 180, 34, 156, 201, 237, 237, 19, 220, 88, 218, 69, 208, 179, 241, 203, 7, 109, 183, 213, 244, 40, 55, 25, 235, 22, 121, 59, 233, 216, 74, 4, 49, 134, 165, 129, 17, 55, 184, 216, 108, 65, 162, 110, 82, 238, 101, 69, 43, 169, 247, 108, 85, 238, 112, 2, 35, 143, 164, 108, 250, 97, 53, 192, 247, 138, 65, 67, 125, 152, 101, 250, 101, 93, 172, 213, 73, 30, 219, 91, 166, 39, 66, 132, 76, 116, 243, 104, 13, 134, 91, 9, 242, 152, 249 };
		retObj.Notes = "gF0j7bqh2JDZrWdSPxiyouStVWwNwKq86De0eqJs3jM0C3XYNkzYzqWkQskX2g8cAU7QCeltC0Nq3FmJSvqpTEvDTiJiSWhwP4p5";
		retObj.ReportsTo = Convert.ToInt32(1);
		retObj.PhotoPath = "7pclUB1dGHJdApG6jMD j4tNIUVklJCPlM0es2sIKYGSLhHH1riFX6DxcaF52duHUlc6uLNuQ9JDcp aotmhOE BFfohC8xLAyMnIOVPWE5l7TrdCTd0XSGT6vhTmqoiRqfkdgmh5cHWP5JTevSU8BYs1HL9ouCg0af5xIIEoSSX3fDdHF3pF4H7JlByC1tjuV84xwOmUjR3CeINZqOalSYyvJs5h9d14A8HerFThGO23wr2iQz1B5SsG7ljFbv";
		// Foreign key entities
		retObj.FK_Employees_Employees_Ref = GetHydratedStaticNorthwind_dbo_Employees();
		return retObj;
	}
}
