/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Orders_Qry GetHydratedStaticNorthwind_dbo_Orders_Qry(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders_Qry();
		retObj.OrderID = (1058123555);
		retObj.CustomerID = "m9hEg";
		retObj.EmployeeID = (1966095841);
		retObj.OrderDate = DateTime.Parse("10/21/1997 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("10/20/2020 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("12/31/1999 12:00:00 AM");
		retObj.ShipVia = (1545660796);
		retObj.Freight = (0.6036706061274419M);
		retObj.ShipName = "HQL85i2spODa9oNGKcv0cPgI0s3ayVP2KdSMz161";
		retObj.ShipAddress = "nmeO1hQo7m0Atdp3cbnlXsnU6rE2sP4naDrQYnn2ngkrTAJ0c96Tj5Tn7cPl";
		retObj.ShipCity = "PCKhglVUunPK8of";
		retObj.ShipRegion = "rbljvhlrwRgiT O";
		retObj.ShipPostalCode = "9Y93TSaZMB";
		retObj.ShipCountry = "lXD7cefsampSjbe";
		retObj.CompanyName = "CdEGQTMrk8 sK4zx4IOHZr36JcjpU DT1XorpErR";
		retObj.Address = "4pKFHndyohjgDmL1nlKljb97QtOtxJZbgGi3I6sBaLVGbNWab3Vne6C6ysvR";
		retObj.City = "sqbmfa6KtfmGklK";
		retObj.Region = "mLqch L NMmCdOc";
		retObj.PostalCode = "htsmFsYGRD";
		retObj.Country = "T5tueeCfdNeYJfT";
		return retObj;
	}
}
