/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Categories GetHydratedStaticNorthwind_dbo_Categories(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Categories();
		retObj.CategoryID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.CategoryName = "cUZhc 0lHRxXRit";
		retObj.Description = "34hGRZ9TX2NzMrOyeOVXSCq66N OucDxysgigt4bieCKXFvxEmvl3uglaYazwZM8lkAgDIvsKEaIlEEMjzgPky3 BdSHM1llciBM";
		retObj.Picture = new Byte[] { 135, 149, 101, 21, 12, 77, 44, 1, 15, 115, 226, 88, 67, 135, 109, 44, 249, 247, 50, 72, 0, 188, 224, 167, 172, 52, 70, 23, 153, 13, 128, 78, 29, 215, 228, 90, 53, 244, 235, 142, 245, 99, 91, 149, 224, 244, 58, 52, 75, 6, 242, 251, 91, 237, 184, 27, 209, 39, 115, 48, 238, 198, 193, 152, 215, 24, 52, 107, 234, 146, 180, 128, 254, 155, 142, 167, 114, 199, 189, 223, 197, 67, 84, 52, 127, 200, 195, 87, 178, 23, 144, 48, 102, 121, 16, 125, 211, 0, 183, 180 };
		return retObj;
	}
}
