/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Order_Details_Extended GetHydratedStaticNorthwind_dbo_Order_Details_Extended(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Order_Details_Extended();
		retObj.OrderID = (-1202141728);
		retObj.ProductID = (-1243400827);
		retObj.ProductName = "dvh3C95wgtygjh96IwZegK1aQxltDczoEGHDB9UI";
		retObj.UnitPrice = (0.23473603772364693M);
		retObj.Quantity = (-29211);
		retObj.Discount = (0.12928551F);
		retObj.ExtendedPrice = (0.9048672302245548M);
		return retObj;
	}
}
