/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Alphabetical_list_of_products GetHydratedStaticNorthwind_dbo_Alphabetical_list_of_products(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Alphabetical_list_of_products();
		retObj.ProductID = (493366792);
		retObj.ProductName = "uX1CD8y9huc7l6GLceyDVN6gi7N6hgZ8 5LfDIhK";
		retObj.SupplierID = (870109134);
		retObj.CategoryID = (1907838186);
		retObj.QuantityPerUnit = "Qu4qr80Ge3YHNQzh7 Ro";
		retObj.UnitPrice = (0.9197854680305256M);
		retObj.UnitsInStock = (-1093);
		retObj.UnitsOnOrder = (-28038);
		retObj.ReorderLevel = (11687);
		retObj.Discontinued = (true);
		retObj.CategoryName = "PBDxczyyvqBhCNn";
		return retObj;
	}
}
