/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Orders GetHydratedStaticNorthwind_dbo_Orders(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders();
		retObj.OrderID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.CustomerID = "RQehb";
		retObj.EmployeeID = Convert.ToInt32(1);
		retObj.OrderDate = DateTime.Parse("9/25/2018 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("7/31/1996 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("8/15/2022 12:00:00 AM");
		retObj.ShipVia = Convert.ToInt32(1);
		retObj.Freight = (0.15481330760334244M);
		retObj.ShipName = "s5ie9lxj8jODCtmAv8PluKKATjgYKdl6M4Tjmc0c";
		retObj.ShipAddress = "ACHFEC9jdygRgq5JYbJnTaZQnGSIE8tzXOLCi2BKnwsAEgFWp87bUR5S9FNq";
		retObj.ShipCity = "LQXoYuwDuuWuckv";
		retObj.ShipRegion = "T 3tp2sdr7CR0x8";
		retObj.ShipPostalCode = "oovQq4p1a1";
		retObj.ShipCountry = "DJvcoaNZzdYzhaG";
		// Foreign key entities
		retObj.FK_Orders_Customers_Ref = GetHydratedStaticNorthwind_dbo_Customers();
		retObj.FK_Orders_Employees_Ref = GetHydratedStaticNorthwind_dbo_Employees();
		retObj.FK_Orders_Shippers_Ref = GetHydratedStaticNorthwind_dbo_Shippers();
		return retObj;
	}
}
