/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Sales_Totals_by_Amount GetHydratedStaticNorthwind_dbo_Sales_Totals_by_Amount(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Sales_Totals_by_Amount();
		retObj.SaleAmount = (0.639402391703M);
		retObj.OrderID = (260094657);
		retObj.CompanyName = "F5hmT4Ag3jZWrkaDhciDY32wTTwqYI7m6zBbKICW";
		retObj.ShippedDate = DateTime.Parse("11/8/2004 12:00:00 AM");
		return retObj;
	}
}
