/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Invoices GetHydratedStaticNorthwind_dbo_Invoices(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Invoices();
		retObj.ShipName = "ObBGzRuC3wans39Wq 0IMDdSHmYnPG32gy40ZnvK";
		retObj.ShipAddress = "wcpeDsE0qVs1WYxdfPtAwc4DUDU5Si0stcAhBHz7nyTgGKSAq OagBir RkC";
		retObj.ShipCity = "VffpJF49BdOj6i5";
		retObj.ShipRegion = "aW4nmeue2j8jkRC";
		retObj.ShipPostalCode = "9LSPJguzh8";
		retObj.ShipCountry = "Tr34Al4NI25tY01";
		retObj.CustomerID = "AsqUS";
		retObj.CustomerName = "A huPmXviFNcs1nrhU5RuHuHNehsvJte5GsCATQG";
		retObj.Address = "gBwInGVqis734JpbBQ7Ttb5ly8bVtpGYV61PbjwH8giDeYGRwzkpU BgFmyN";
		retObj.City = "xoDKGYaNh11B0Hv";
		retObj.Region = "4a4hOfa6ZQKjGYh";
		retObj.PostalCode = "lhxHB0WyJV";
		retObj.Country = "85EjOU JeGl6tKh";
		retObj.Salesperson = "omt7tI bnah8ziDV0WkPtos6N3JhO6W";
		retObj.OrderID = (1328062340);
		retObj.OrderDate = DateTime.Parse("10/30/2022 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("10/3/2016 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("1/14/2004 12:00:00 AM");
		retObj.ShipperName = "UUHWXt8ySyTVqPNAWyZL3xfZ XlRF9klegUSjT17";
		retObj.ProductID = (5704664);
		retObj.ProductName = "LjhpY1Q8pCQV4pNmqLu ddzPMfihC4sctUxNTeAq";
		retObj.UnitPrice = (0.5326593967916137M);
		retObj.Quantity = (-26368);
		retObj.Discount = (0.8507655F);
		retObj.ExtendedPrice = (0.9107314098816852M);
		retObj.Freight = (0.16606795797904972M);
		return retObj;
	}
}
