/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Sales_by_Category GetHydratedStaticNorthwind_dbo_Sales_by_Category(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Sales_by_Category();
		retObj.CategoryID = (-2024330763);
		retObj.CategoryName = "WLzsht0mDE VvUi";
		retObj.ProductName = "bihS0JvpvYc9KH4hHqz2DoumocL5j0emFy4QXtY4";
		retObj.ProductSales = (0.10785505412670326M);
		return retObj;
	}
}
