/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Customers GetHydratedStaticNorthwind_dbo_Customers(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Customers();
		retObj.CustomerID = (fillPrimaryKey ? "z81WI" : String.Empty);
		retObj.CompanyName = "tkNfouSopSb hyj2dhh2O1gcNHCCYySaTlYfOIyn";
		retObj.ContactName = "ZEnROTb83Gt3GOqf YKVfdyKt2WtTA";
		retObj.ContactTitle = "ecxSHdVbIjokJtAo5XCDeBzE0CcvWM";
		retObj.Address = "1s5hfyb8CPwk36Wku1MIjmtURF48uDq3sVGKVl2ZsiCYXvZO1SVdqM9ewSL ";
		retObj.City = "P AzhHlbjGxkzf6";
		retObj.Region = "vbiP6RnL8bAdSWu";
		retObj.PostalCode = "rZ2XVxHMGh";
		retObj.Country = "hISJjGLGR0vx1Z2";
		retObj.Phone = "5iFs2QrioxgnGtiHj a9nkRS";
		retObj.Fax = "sKi2JFaUl9n5LcKAUtfEzJ07";
		return retObj;
	}
}
