/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Quarterly_Orders GetHydratedStaticNorthwind_dbo_Quarterly_Orders(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Quarterly_Orders();
		retObj.CustomerID = "h5iA0";
		retObj.CompanyName = "mIrr5NXXhEsnOoHejfBA0HQbg1g9yTmEP4jb28dI";
		retObj.City = "rxmgnQ1cOdrXkU7";
		retObj.Country = "HjrUDw2ktpadyS1";
		return retObj;
	}
}
