/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Customers(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Customers_IR();
	retObj.CustomerID = (fillPrimaryKey ? 'iY9Ad' : null);
	retObj.CompanyName = 'ZKfXLMv0ILnTthUCqwfqn2LB4SMZLRY5wU01mYYW';
	retObj.ContactName = '2fOJ7 6So3gt218wRtWDP4EY4bBnLN';
	retObj.ContactTitle = '3EwZ5AysSHJjYAwV1GDldDD8A4oLWk';
	retObj.Address = 'FgrUZ7DES JqmfLj7dXayOU3Qii876GNpJgFayCE0aAGuzWTjTbPBgZBH5m9';
	retObj.City = 'PjNJm7wa6Ih0PEr';
	retObj.Region = 'acju46bZ7CToVJ6';
	retObj.PostalCode = 'stcpR1Uj8E';
	retObj.Country = 'nG2jUen SGCxKS9';
	retObj.Phone = '3IahlmVbvtdVfgjh8kfm2FWP';
	retObj.Fax = 'EgfC7rq6wCIPjh0CEPaBc0fu';
	return retObj;
}
