/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Suppliers(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Suppliers_IR();
	retObj.SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CompanyName = 'tU4gOABA15mU3mY6YjhaeIFADrCmzjT8eEhc23b8';
	retObj.ContactName = '9wQvajHy0JgaZ7UDnKT1NTW6qPyBEF';
	retObj.ContactTitle = '7cNkzYZE1dxHHPWW22qTerATi86zNT';
	retObj.Address = 'elj5ICgIu1AfKuDB1rXtq68PeIJwBjWpK85uQFdW25hc yMcXTEyT8WDaAyi';
	retObj.City = 'cdw813vQk69RpeL';
	retObj.Region = 'zC9rU5yh0Z9QMpx';
	retObj.PostalCode = 'fGCleEQ8kH';
	retObj.Country = 'HqhR0yy3D0j7g6R';
	retObj.Phone = 'xSU5qGbwz9NDJJ69g7Gfvmrs';
	retObj.Fax = 'tbIFrByQthQrTZxBsLNeryRg';
	retObj.HomePage = '6eWm pPZoe3a1ZeFCqX00092DKTQJMzRIkuGSPI4TgeLxLQlWyhNEHonn6gg4PUOC2SYllsSljCyUpiLMiTGWKG3Ap3gEVqG5NVX';
	return retObj;
}
