/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Categories(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Categories_IR();
	retObj.CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CategoryName = 'oDUxCbJ5megYRE9';
	retObj.Description = 'OI7dyCUyVLwH7MP0TP1NMmDaWTNLqG0Up9O5lCaapgeSL2KAbb1MdVc3LHVJOZIxIkixxiJ2xTHt0AU7MiGB1RRgnfqLHMAUMsnY';
	retObj.Picture = new Int8Array([109,124,197,19,97,86,144,61,187,28,229,85,163,122,141,108,205,122,65,219,114,211,109,185,108,247,251,193,104,121,171,43,186,0,99,198,41,39,205,79,55,177,142,202,239,197,3,22,14,122,224,114,229,219,115,73,163,102,116,252,235,164,22,143,3,27,185,88,176,171,32,167,121,106,83,105,122,108,12,184,20,129,203,193,104,226,6,33,6,59,235,22,166,241,36,251,140,148,139,14]);
	return retObj;
}
