/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Customer_and_Suppliers_by_City(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Customer_and_Suppliers_by_City_IR();
	retObj.City = 'k0PfvqfG1t4Hx1z';
	retObj.CompanyName = '2ebwWR21fklLCOV3j8KsWf0C7jDoGh1 AE6w7OKt';
	retObj.ContactName = '4pLrkZrKxZyaekvvFitsWB1tfvbjxL';
	retObj.Relationship = 'o9PM11IUS';
	return retObj;
}
