/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Orders_Qry(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Orders_Qry_IR();
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CustomerID = (fillPrimaryKey ? 'xOMdp' : null);
	retObj.EmployeeID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.OrderDate = '/Date(4/1/2013 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(3/25/2006 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(11/11/2004 12:00:00 AM)/';
	retObj.ShipVia = 1019762227;
	retObj.Freight = 0.6119643392450264;
	retObj.ShipName = ' 5Y5rKhFdk0fFdTBjGE9YvPQUPKjUAmrvkFlatkf';
	retObj.ShipAddress = 'ljCJDSkNeAspTw67ourDihcgC9ggVPtC8BgKUS9kc2BU4DOATZGOXUQf6Ezb';
	retObj.ShipCity = '9bFOIjmQ15iLOVc';
	retObj.ShipRegion = 'wwbGm8Ere2BIXAA';
	retObj.ShipPostalCode = 'n0nEJZUlO2';
	retObj.ShipCountry = 'mrxLnZQKDnhPVY8';
	retObj.CompanyName = 'xNLVea7N9BY7yboNmI4xSznJEiYj6InzMm ANJuA';
	retObj.Address = '0dDgbdKaLUsiwBhOlfqsjKspR4jrHCR2AbyThRQVM1goeeoksn5XDfTCnwhe';
	retObj.City = 'ttNmsL3U8TwtbpR';
	retObj.Region = 'mWcj8uZQbNKV NK';
	retObj.PostalCode = 'rJv7ONNZ3p';
	retObj.Country = 'kQJ3oIdk2cfe9Cl';
	return retObj;
}
