/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Orders(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Orders_IR();
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CustomerID = 'HXNdt';
	retObj.EmployeeID_IR = encrypt(1);
	retObj.OrderDate = '/Date(2/24/1997 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(9/12/2015 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(9/19/2019 12:00:00 AM)/';
	retObj.ShipVia_IR = encrypt(1);
	retObj.Freight = 0.6666069497224202;
	retObj.ShipName = 'v75RXv41j4CVh uvD4irgB1KTBdue3oN8a02wqbl';
	retObj.ShipAddress = 'dJlfJwNGsanGgWv46FRD52beERunBlGDsLMfalCxLSZkYvmQiy7Y2pZWbjbp';
	retObj.ShipCity = 'vLv0DS0 OyHA06J';
	retObj.ShipRegion = '8M9rU3bjDADhzQ4';
	retObj.ShipPostalCode = '6RplB2dihz';
	retObj.ShipCountry = '9RIZ8sQGattlavB';
	// Foreign key entities
	retObj.FK_Orders_Customers_Ref_IR = getHydratedStaticNorthwind_dbo_Customers_IR();
	retObj.FK_Orders_Employees_Ref_IR = getHydratedStaticNorthwind_dbo_Employees_IR();
	retObj.FK_Orders_Shippers_Ref_IR = getHydratedStaticNorthwind_dbo_Shippers_IR();
	return retObj;
}
