/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Products_Above_Average_Price(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Products_Above_Average_Price_IR();
	retObj.ProductName = 'rGr1KwJlqu KF9q2OthYobytYcXpQniaBwfY9Jv0';
	retObj.UnitPrice = 0.9861907116320202;
	return retObj;
}
