/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Alphabetical_list_of_products(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Alphabetical_list_of_products_IR();
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = 'jt7Qe5nztny07TSvmObZUf6ClpRuF1H1SU6rCsgZ';
	retObj.SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.QuantityPerUnit = 'egukbqLu CLWm CjvC9w';
	retObj.UnitPrice = 0.627570264827677;
	retObj.UnitsInStock = -20290;
	retObj.UnitsOnOrder = -11032;
	retObj.ReorderLevel = -28251;
	retObj.Discontinued = false;
	retObj.CategoryName = 'utljDCPi pJE60H';
	return retObj;
}
