/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Invoices(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Invoices_IR();
	retObj.ShipName = 'cypJ3vyEZu940eFFapuADL87rt1ixQbbSgVY2ETg';
	retObj.ShipAddress = 'HcgAcVwNSmSvI0I BDta2mWWfKwTHhZOMvkbSaWwk7ByNQgg 6S31b4JBasL';
	retObj.ShipCity = 'fuGGmHrvuQZHJ6d';
	retObj.ShipRegion = 'TmKtVMlMJaNoC10';
	retObj.ShipPostalCode = 'IiRdWEIKRP';
	retObj.ShipCountry = 'qZOx5dWToPA2i70';
	retObj.CustomerID = (fillPrimaryKey ? 'k955D' : null);
	retObj.CustomerName = 'mXDUnRlN72H7OjL4T8ylPUjaZBPQY26wO5LCObj7';
	retObj.Address = 'zu3aJ FA5oAKY4kP4Uza voTvI6nscPBszkDAn 2 3qSVQt0IHSjU95rSaQY';
	retObj.City = 'UU7C9 MepjDT4es';
	retObj.Region = 'j9URPTKMtlrdQvt';
	retObj.PostalCode = 'WqbKimRNgR';
	retObj.Country = '5ASJIouuyFvP62R';
	retObj.Salesperson = 'YiIi4HEcct7ZUA6KLXc9jh0fn41TdWy';
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.OrderDate = '/Date(11/7/2013 12:00:00 AM)/';
	retObj.RequiredDate = '/Date(2/26/2012 12:00:00 AM)/';
	retObj.ShippedDate = '/Date(11/23/2022 12:00:00 AM)/';
	retObj.ShipperName = 'VLkdexPtOiMqxexzBIfyIz EmZLsZfTyEsX6eYOh';
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = 'IXi7NqDs Dr7an92Y9IxK5AGf8cYjrmpeCj3xRTI';
	retObj.UnitPrice = 0.08490631595029985;
	retObj.Quantity = -32674;
	retObj.Discount = 0.75637925;
	retObj.ExtendedPrice = 0.6191497151805819;
	retObj.Freight = 0.622660109986451;
	return retObj;
}
