/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Products(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Products_IR();
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = '7L983NKbKIhMQyj5r7Y48Cr2Sd0Luk2G5fKeRbvt';
	retObj.SupplierID_IR = encrypt(1);
	retObj.CategoryID_IR = encrypt(1);
	retObj.QuantityPerUnit = '1d6yHU5g66W fJgyF8wQ';
	retObj.UnitPrice = 0.7135930972579689;
	retObj.UnitsInStock = 2481;
	retObj.UnitsOnOrder = -12704;
	retObj.ReorderLevel = -27720;
	retObj.Discontinued = false;
	// Foreign key entities
	retObj.FK_Products_Categories_Ref_IR = getHydratedStaticNorthwind_dbo_Categories_IR();
	retObj.FK_Products_Suppliers_Ref_IR = getHydratedStaticNorthwind_dbo_Suppliers_IR();
	return retObj;
}
