/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Products_by_Category(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Products_by_Category_IR();
	retObj.CategoryName = 'rTpCywtTzY7jy 3';
	retObj.ProductName = '5zVQtvylDGfX0a3mNEYLYIPYwemrmTjOtUi8ls3r';
	retObj.QuantityPerUnit = '7TsqOpYKMgbCGJNhHhUX';
	retObj.UnitsInStock = 20308;
	retObj.Discontinued = true;
	return retObj;
}
