/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Employees(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Employees_IR();
	retObj.EmployeeID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.LastName = 'MLMEA45HWMGhIFI1HHyA';
	retObj.FirstName = 'YNshkV yGd';
	retObj.Title = 'wXbEhWqCzgpXmHVEpwtlvfEWUCY880';
	retObj.TitleOfCourtesy = 'myuSozq40pb3c BwDRvPv3gT9';
	retObj.BirthDate = '/Date(12/10/2005 12:00:00 AM)/';
	retObj.HireDate = '/Date(2/18/1998 12:00:00 AM)/';
	retObj.Address = 'H0CyDBznqZGjwLlaI6L2ctywTkWdhulg1n9CAVTM16F2pR 9LO2gZJq9AO3q';
	retObj.City = 'V7aUdrJCILx2rcU';
	retObj.Region = 'wtd05ul0UJHc9HL';
	retObj.PostalCode = 'vd7ppke5Kk';
	retObj.Country = 'FF4SARh7hby  3c';
	retObj.HomePhone = '6iCbNufJFh2PmwWD74J1sqDj';
	retObj.Extension = '2QKW';
	retObj.Photo = new Int8Array([251,28,195,86,220,226,130,207,216,44,244,114,127,61,93,34,86,197,75,241,9,21,94,220,229,109,183,117,137,96,204,215,107,45,61,75,249,7,13,119,105,189,211,137,9,237,211,90,168,218,155,62,148,130,98,71,213,83,195,159,199,220,50,107,35,215,104,17,152,37,91,157,71,90,127,226,115,175,151,226,138,243,29,202,120,146,185,200,137,111,26,6,184,229,225,88,185,26,190,227]);
	retObj.Notes = 'P8XEzWD77dID4lqwy9R0LaBw6D0wymVh nX2G12nYhQ7r2qwgw62HPhDszfQCqmiliK6Jqhb65arrx y8TO1lOVoLF2TrTYYrl2q';
	retObj.ReportsTo_IR = encrypt(1);
	retObj.PhotoPath = 'LBMf8tNvVc0u6jjKYcBI93 p7Z9f8UG1CndnrJIinNSAlAdiLPFV3ONbrGh9ta0rUcOFonvFiUiQWibK8OphSTy55sUgt3tvIz1WVYQMFi4vAZU1hnp1LuwJglTqSdzsMEJ1Vkr4Qb4IPNElDtT9gmd2fUmc97dOhHX7GRMDt4J5cxRda6pKUPBkQpCWpsz9g8vZD Mm4YCmhZSVpKwJqz5LLbB4L7fQogy0vG7PYeODLSUDlD5MbVRcB5pJcQ0';
	// Foreign key entities
	retObj.FK_Employees_Employees_Ref_IR = getHydratedStaticNorthwind_dbo_Employees_IR();
	return retObj;
}
