/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_EMPLOYEES(fillPrimaryKey = false) {
	let retObj = new XE_HR_EMPLOYEES_IR();
	retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.FIRST_NAME = 'X4wpKjAGYGX7fGokO7DZ';
	retObj.LAST_NAME = 'AJU5Ysi9YLPDV4vEGY5kW1DTP';
	retObj.EMAIL = 'owxbK1pteHYga2vWrsdNJQ2cB';
	retObj.PHONE_NUMBER = 'EOb0XSomEYi9MIztj81E';
	retObj.HIRE_DATE = '/Date(8/2/1997 12:00:00 AM)/';
	retObj.JOB_ID = 'l6ujcPpzGj';
	retObj.SALARY = 0.1347426040413543;
	retObj.COMMISSION_PCT = 0.12473856508308978;
	retObj.MANAGER_ID_IR = encrypt(1);
	retObj.DEPARTMENT_ID_IR = encrypt(1);
	// Foreign key entities
	retObj.EMP_DEPT_FK_Ref_IR = getHydratedStaticXE_HR_DEPARTMENTS_IR();
	retObj.EMP_JOB_FK_Ref_IR = getHydratedStaticXE_HR_JOBS_IR();
	retObj.EMP_MANAGER_FK_Ref_IR = getHydratedStaticXE_HR_EMPLOYEES_IR();
	return retObj;
}
