/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_JOBS(fillPrimaryKey = false) {
	let retObj = new XE_HR_JOBS_IR();
	retObj.JOB_ID = (fillPrimaryKey ? 'c3isDpDdr3' : null);
	retObj.JOB_TITLE = 'm07jwFNfTSFeBmWfpJVdQcMwdO0teKtBiwi';
	retObj.MIN_SALARY = -1741764183;
	retObj.MAX_SALARY = 1505709886;
	return retObj;
}
