/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_PACKAGE1_PARAMOUTCURSORS(fillPrimaryKey = false) {
	var retObj = new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_IR();
		// Output parameters
	retObj.CONVERTED_TO_VARCHAR2 = '7dY6zCGCwEW lfADAFxWtJran1YEjzBap0s3xhoKhQsdvDqtRW76ppbgqEDeUyOZfzkV43ZiE WU 4o1gRV W4MDftjFgruNg 3p';
	retObj.Query1_Results_IR.ToList().push({});
	retObj.query1_Results_IR[0].EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].START_DATE = 'g7H6faN';
	retObj.query1_Results_IR[0].END_DATE = 'VnFvgBG';
	retObj.query1_Results_IR[0].JOB_ID = 'P xSM7rl8b';
	retObj.query1_Results_IR[0].DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.Query2_Results_IR.ToList().push({});
	retObj.query2_Results_IR[0].DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query2_Results_IR[0].DEPARTMENT_NAME = 'ZY4V5V8L0zluB3l7w8bEcdiC4HPET7';
	retObj.query2_Results_IR[0].MANAGER_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query2_Results_IR[0].LOCATION_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	return retObj;
}
