/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_EMP_DETAILS_VIEW(fillPrimaryKey = false) {
	let retObj = new XE_HR_EMP_DETAILS_VIEW_IR();
	retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.JOB_ID = (fillPrimaryKey ? 'D1l84NJqls' : null);
	retObj.MANAGER_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.LOCATION_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.COUNTRY_ID = (fillPrimaryKey ? 'ii' : null);
	retObj.FIRST_NAME = 'jO2PwYfWeb0nL4JmRPnj';
	retObj.LAST_NAME = 'tM2pBeEldE4LpKZ5g2SaEKzTL';
	retObj.SALARY = 0.212963906173397;
	retObj.COMMISSION_PCT = 0.3184524492910805;
	retObj.DEPARTMENT_NAME = 'CAIhfreRbOPAONb5KHeyPB5H5EHwrU';
	retObj.JOB_TITLE = 'ipnFmAxwzN4KBwggMj3RgfzwVyvFk2ZjYRe';
	retObj.CITY = 'yZ1t3yrWxScLAij34SNBBFXlEF72E0';
	retObj.STATE_PROVINCE = 'grlW9r 6VQAGxeteybeAChM7k';
	retObj.COUNTRY_NAME = 'NF4hOz8wB6RsNcUL7X0D7gbvurRq0HCTuvNTMbrB';
	retObj.REGION_NAME = 'O PnWIUzDWm0h2bGQMuXS8yBq';
	return retObj;
}
