/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_PACKAGE1_OPEN_ONE_CURSOR(fillPrimaryKey = false) {
	var retObj = new XE_HR_PACKAGE1_OPEN_ONE_CURSOR_OM_IR();
	retObj.Query1_Results_IR.ToList().push({});
	retObj.query1_Results_IR[0].EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].JOB_ID = 'GMev9gHUnW';
	retObj.query1_Results_IR[0].MANAGER_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].LOCATION_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].COUNTRY_ID = 'YA';
	retObj.query1_Results_IR[0].FIRST_NAME = '4V0t oF27VDVbfKStZ28';
	retObj.query1_Results_IR[0].LAST_NAME = 'tdOaEqBPHNiUPmAJ NBectFRL';
	retObj.query1_Results_IR[0].SALARY = 0.23790624996665477;
	retObj.query1_Results_IR[0].COMMISSION_PCT = 0.8529181703055249;
	retObj.query1_Results_IR[0].DEPARTMENT_NAME = '09ej4SrG31kQgxwQhKPFMjMHikv3HK';
	retObj.query1_Results_IR[0].JOB_TITLE = 'vjjHNMlpWp0yjhOgK0roAe0cj7qPXqS4wHQ';
	retObj.query1_Results_IR[0].CITY = 'SQyEJMUTYUKTkS8kN2Ha4ZjLrBuXL3';
	retObj.query1_Results_IR[0].STATE_PROVINCE = '3vPm6fUgDAPvEApIxesRqKcE ';
	retObj.query1_Results_IR[0].COUNTRY_NAME = 'uc2vA0MYehBUlcqwaz Wwv1ZiiXMQwGFfmfqFeFS';
	retObj.query1_Results_IR[0].REGION_NAME = '1bbvo5MB fXgo3vVohbrFvXFS';
	return retObj;
}
