/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR(fillPrimaryKey = false) {
	var retObj = new XE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR_OM_IR();
		// Output parameters
	retObj.FunctionReturnParam = 'RkFgWZc1cfFvfQSQRPtp ZDqjzpWvTNtoHHG3v087m1WDdDuXMu9ULPzvwF5Not kWP0 z8VZGo6PYPXt874Czhn2D2Z0OLLiFCD';
	return retObj;
}
