/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_PACKAGE1_OPEN_TWO_CURSORS(fillPrimaryKey = false) {
	var retObj = new XE_HR_PACKAGE1_OPEN_TWO_CURSORS_OM_IR();
	retObj.Query1_Results_IR.ToList().push({});
	retObj.query1_Results_IR[0].EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].FIRST_NAME = 'GmJOt sOuOr2ahk a1jN';
	retObj.query1_Results_IR[0].LAST_NAME = 'j8GBmJ8pCRsPLGWodcLoPmDN9';
	retObj.query1_Results_IR[0].EMAIL = 'VezZAxXTzxlif4OcXEMlyvL9Z';
	retObj.query1_Results_IR[0].PHONE_NUMBER = 'JYlCqzolyfCo4Y27WWeU';
	retObj.query1_Results_IR[0].HIRE_DATE = 'nLHLlSs';
	retObj.query1_Results_IR[0].JOB_ID = 'dnVMRKylp2';
	retObj.query1_Results_IR[0].SALARY = 0.1922321292792304;
	retObj.query1_Results_IR[0].COMMISSION_PCT = 0.08186954243241684;
	retObj.query1_Results_IR[0].MANAGER_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.Query2_Results_IR.ToList().push({});
	retObj.query2_Results_IR[0].DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query2_Results_IR[0].DEPARTMENT_NAME = 'eMIfUVWmuC9LHNZvrs9AkXvPKQsiBA';
	retObj.query2_Results_IR[0].MANAGER_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query2_Results_IR[0].LOCATION_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	return retObj;
}
