/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_COUNTRIES(fillPrimaryKey = false) {
	let retObj = new XE_HR_COUNTRIES_IR();
	retObj.COUNTRY_ID = (fillPrimaryKey ? 'zP' : null);
	retObj.COUNTRY_NAME = 'jVGI H sGeFCWXDMXVrdD3HOiQ5Vuf3lsSg5XRQd';
	retObj.REGION_ID_IR = encrypt(1);
	// Foreign key entities
	retObj.COUNTR_REG_FK_Ref_IR = getHydratedStaticXE_HR_REGIONS_IR();
	return retObj;
}
