/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_ProductsAndCategories_OM GetHydratedStaticNorthwind_dbo_ProductsAndCategories_OM(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_ProductsAndCategories_OM();
		retObj.Query1_Results!.ToList().Add(new Northwind_dbo_ProductsAndCategories_OM_Query1());
		retObj.Query1_Results!.First()!.ProductID = Convert.ToInt32(1);
		retObj.Query1_Results!.First()!.ProductName = "34ptFgWEG1f4uh8pvZ0Zw5fyqgyY2mxm2njhgwIt";
		retObj.Query1_Results!.First()!.SupplierID = Convert.ToInt32(1);
		retObj.Query1_Results!.First()!.CategoryID = Convert.ToInt32(1);
		retObj.Query1_Results!.First()!.QuantityPerUnit = "FGmrM8K9EWzDqX3Kcv4U";
		retObj.Query1_Results!.First()!.UnitPrice = (0.30532929478814086M);
		retObj.Query1_Results!.First()!.UnitsInStock = (10014);
		retObj.Query1_Results!.First()!.UnitsOnOrder = (14630);
		retObj.Query1_Results!.First()!.ReorderLevel = (5699);
		retObj.Query1_Results!.First()!.Discontinued = (true);
		retObj.Query2_Results!.ToList().Add(new Northwind_dbo_ProductsAndCategories_OM_Query2());
		retObj.Query2_Results!.First()!.CategoryID = Convert.ToInt32(1);
		retObj.Query2_Results!.First()!.CategoryName = "iYbkPZBteb285Su";
		retObj.Query2_Results!.First()!.Description = "DJnt 0bMpxOztIAzfG0c72ZpWzSw7uL4bCAcZ TnNiq4oIID32LPhqilFO4eyHWQoZVzQt2uOO0WXbtp8JRk FGkDhnhRd11uUIV";
		retObj.Query2_Results!.First()!.Picture = new Byte[] { 232, 173, 153, 64, 84, 82, 162, 194, 60, 23, 143, 40, 131, 122, 37, 125, 112, 183, 215, 17, 211, 250, 195, 96, 224, 85, 64, 75, 223, 52, 185, 196, 192, 166, 107, 50, 103, 184, 132, 28, 209, 247, 173, 5, 182, 1, 8, 5, 151, 65, 148, 21, 196, 76, 162, 54, 30, 113, 41, 250, 126, 167, 74, 240, 76, 185, 107, 117, 76, 143, 56, 87, 249, 16, 161, 44, 23, 243, 1, 169, 88, 69, 172, 118, 186, 52, 81, 139, 85, 114, 172, 212, 109, 109, 121, 44, 117, 104, 41, 117 };
		return retObj;
	}
}
