/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Categories GetHydratedStaticNorthwind_dbo_Categories(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Categories();
		retObj.CategoryID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.CategoryName = "MQWIxTn4FRBGUrV";
		retObj.Description = "UeTD9ljcC25NJKFtN47I LwyvzIPfJE X37rfKWMkCRZmQgORPMB7X67Ds1HOcb01CR FqHwR5hXdyPaAwXFgAGegztp0JuvEzOp";
		retObj.Picture = new Byte[] { 220, 236, 242, 240, 162, 245, 145, 89, 138, 205, 150, 79, 85, 152, 216, 155, 81, 229, 192, 169, 15, 237, 83, 24, 162, 200, 121, 118, 179, 170, 234, 62, 231, 246, 99, 27, 168, 152, 145, 63, 141, 59, 9, 196, 105, 208, 94, 43, 16, 14, 250, 143, 190, 2, 234, 60, 144, 216, 80, 174, 38, 186, 79, 93, 252, 59, 164, 140, 149, 91, 255, 25, 2, 119, 113, 129, 243, 0, 137, 227, 56, 39, 178, 151, 161, 40, 5, 134, 109, 166, 5, 240, 29, 198, 176, 24, 33, 101, 232, 202 };
		return retObj;
	}
}
