/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Orders GetHydratedStaticNorthwind_dbo_Orders(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders();
		retObj.OrderID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.CustomerID = "5incK";
		retObj.EmployeeID = Convert.ToInt32(1);
		retObj.OrderDate = DateTime.Parse("11/25/2006 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("9/6/2020 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("7/2/2010 12:00:00 AM");
		retObj.ShipVia = Convert.ToInt32(1);
		retObj.Freight = (0.2719547232135521M);
		retObj.ShipName = "LL3E0s59UtaSZsgvkIQT81LlLTrcEr1gwYgCQOxT";
		retObj.ShipAddress = "jBDGqYv89GgX997TVX22mm16M3svv2DyLKeelS2Ce4jTWaxrJNCpJejx1McR";
		retObj.ShipCity = "g5sjTknFApWkszO";
		retObj.ShipRegion = "91Upwbxbd15RqKX";
		retObj.ShipPostalCode = "53Y2Ts0c9i";
		retObj.ShipCountry = "AJ6Fz8ZPgRxXUCy";
		// Foreign key entities
		retObj.FK_Orders_Customers_Ref = GetHydratedStaticNorthwind_dbo_Customers();
		retObj.FK_Orders_Employees_Ref = GetHydratedStaticNorthwind_dbo_Employees();
		retObj.FK_Orders_Shippers_Ref = GetHydratedStaticNorthwind_dbo_Shippers();
		return retObj;
	}
}
