/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Order_Details_Extended GetHydratedStaticNorthwind_dbo_Order_Details_Extended(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Order_Details_Extended();
		retObj.OrderID = (-393735260);
		retObj.ProductID = (-1725923271);
		retObj.ProductName = "Ubm75E36vlQqLp w9fMRoJU09rHfyd6nvX4RzC 7";
		retObj.UnitPrice = (0.8148707329168509M);
		retObj.Quantity = (-28678);
		retObj.Discount = (0.41309285F);
		retObj.ExtendedPrice = (0.7631525279725542M);
		return retObj;
	}
}
