/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Alphabetical_list_of_products GetHydratedStaticNorthwind_dbo_Alphabetical_list_of_products(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Alphabetical_list_of_products();
		retObj.ProductID = (-1771476669);
		retObj.ProductName = "yRNNBCe csEuqLUKH6vwV8qfA8f8XQctz8gq9uTI";
		retObj.SupplierID = (1983368215);
		retObj.CategoryID = (960897978);
		retObj.QuantityPerUnit = "KhbEXkUTTgcvmjX8CBXy";
		retObj.UnitPrice = (0.27685126833335383M);
		retObj.UnitsInStock = (-13631);
		retObj.UnitsOnOrder = (-32638);
		retObj.ReorderLevel = (4604);
		retObj.Discontinued = (false);
		retObj.CategoryName = "e9Y3HSdbwtwFIqx";
		return retObj;
	}
}
