/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Sales_Totals_by_Amount GetHydratedStaticNorthwind_dbo_Sales_Totals_by_Amount(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Sales_Totals_by_Amount();
		retObj.SaleAmount = (0.35282639100377744M);
		retObj.OrderID = (-645884871);
		retObj.CompanyName = "DDYsygjaX8sH5AXqEqtj9hqIdZyh5GJ6sapqqoyh";
		retObj.ShippedDate = DateTime.Parse("11/10/2005 12:00:00 AM");
		return retObj;
	}
}
