/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Category_Sales_for_1997 GetHydratedStaticNorthwind_dbo_Category_Sales_for_1997(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Category_Sales_for_1997();
		retObj.CategoryName = "HHACCUcoyNR6qPg";
		retObj.CategorySales = (0.7228350166089773M);
		return retObj;
	}
}
