/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Customer_and_Suppliers_by_City GetHydratedStaticNorthwind_dbo_Customer_and_Suppliers_by_City(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Customer_and_Suppliers_by_City();
		retObj.City = "S2bVJ0yxpnWTO9R";
		retObj.CompanyName = "W1a5Y1wx zEC3FM4PtP3dca26Da9wI7oFNI0DLzV";
		retObj.ContactName = "DCtsyPqPFcWWhwBsxpWoLVRPMmHLii";
		retObj.Relationship = "TQ6ese1Sy";
		return retObj;
	}
}
