/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Invoices GetHydratedStaticNorthwind_dbo_Invoices(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Invoices();
		retObj.ShipName = "MCoMl9QIelE8O2h2Q7NMDP8XN9PqLI6cLTNjD39P";
		retObj.ShipAddress = "JsApERVwS8BqxmgtK03gRJryg1Q71yhDRL9F9hFxOlFkE4XTwN4Za1K5umqy";
		retObj.ShipCity = "NITNN9LnfX8M3dk";
		retObj.ShipRegion = "LnpCnD6YrcAsbSU";
		retObj.ShipPostalCode = "fvO45ievCI";
		retObj.ShipCountry = "mpoZI6a1xL4xO3x";
		retObj.CustomerID = "4bCG7";
		retObj.CustomerName = "p6xoK5SSB4CiS5y0aro0qC24EkOd4DP8jBLRzJSe";
		retObj.Address = "68bTb9GwtAtaUu2galQNDWN4Tv32kuzKy9D0yXMZ9cJeyKJ3XHvKh0YamTxa";
		retObj.City = "gqQMsr KQCf6oXI";
		retObj.Region = "5n0mvSOx9jll3Mj";
		retObj.PostalCode = "6fL565Jb5i";
		retObj.Country = "wy6ITGQlKZAwYNK";
		retObj.Salesperson = "0AfSmPO9mqkG2l4XispoVV5kZ8qo7FD";
		retObj.OrderID = (1974428228);
		retObj.OrderDate = DateTime.Parse("12/23/2008 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("7/21/2006 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("9/30/2004 12:00:00 AM");
		retObj.ShipperName = "Nnl7KVOLZYaqE3sQlhwWJGMAA1tXqBouL0rlLbD3";
		retObj.ProductID = (1860273732);
		retObj.ProductName = "YrvlNgQ4y nNVglk5PAVaabuTVja0i1stxUq6tNf";
		retObj.UnitPrice = (0.11130867310873982M);
		retObj.Quantity = (-21730);
		retObj.Discount = (0.5922575F);
		retObj.ExtendedPrice = (0.4837551219695829M);
		retObj.Freight = (0.7215888820987426M);
		return retObj;
	}
}
