/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Orders_Qry GetHydratedStaticNorthwind_dbo_Orders_Qry(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders_Qry();
		retObj.OrderID = (323516033);
		retObj.CustomerID = "jndfT";
		retObj.EmployeeID = (171250773);
		retObj.OrderDate = DateTime.Parse("2/1/2008 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("11/18/2008 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("12/14/2002 12:00:00 AM");
		retObj.ShipVia = (-800063287);
		retObj.Freight = (0.8641492793942595M);
		retObj.ShipName = "8 LB0tawLugsq9steeLlTY kR7WATZsX8aExtrux";
		retObj.ShipAddress = "JZwKlMgLxFyh8YheAFtHdNOozpaTvPaGnG9uYQlHJNjKhf12DH9BOsTX7Kv4";
		retObj.ShipCity = "rCzpVhGYUVI9o8q";
		retObj.ShipRegion = "NOUMjBURBosfX6Z";
		retObj.ShipPostalCode = "snw8FplhH2";
		retObj.ShipCountry = "xi Ml7u1IBDZ Xy";
		retObj.CompanyName = "dp9wu0IOJut6uht6Hmw3LcB64ZIrBUSza6nIFgKP";
		retObj.Address = "oM8WCQKivXKcBLpuxTrugfTjLnnxJwxNbL6g4pVg4JADQPoDtvMbxFqYiE4J";
		retObj.City = "966mdYF5n4H1ulK";
		retObj.Region = "1M6H14BuSaXShXm";
		retObj.PostalCode = "KkktrwZjFw";
		retObj.Country = "jI9lumquZjGxRz3";
		return retObj;
	}
}
