/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_CustOrdersOrders_OM GetHydratedStaticNorthwind_dbo_CustOrdersOrders_OM(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_CustOrdersOrders_OM();
		retObj.OrderID = Convert.ToInt32(1);
		retObj.OrderDate = DateTime.Parse("11/29/2000 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("5/22/1996 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("12/20/2014 12:00:00 AM");
		return retObj;
	}
}
