/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Employees GetHydratedStaticNorthwind_dbo_Employees(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Employees();
		retObj.EmployeeID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.LastName = "UhHsJnF7GuBFCSuo37WV";
		retObj.FirstName = "W2HKXoWMee";
		retObj.Title = "TDT9sUL33rlxYIgGQ5EvWo7ia5HA z";
		retObj.TitleOfCourtesy = "B8GD 3z6b4TIIrqRrLuxCsd4M";
		retObj.BirthDate = DateTime.Parse("3/12/2010 12:00:00 AM");
		retObj.HireDate = DateTime.Parse("4/14/2003 12:00:00 AM");
		retObj.Address = "BCesw6 pvUl4hMNujS3Pe1zipoAI2NGlZ7EQPvIpr 2qdQmPdm71eThWc7rF";
		retObj.City = "kxWlu8AJbtKc4OI";
		retObj.Region = "vL3wm1l54DYtEEE";
		retObj.PostalCode = "qPbWoQMPr7";
		retObj.Country = "meOnOQXoGh XEnp";
		retObj.HomePhone = "ITuCnxH 7GIzvroxI4BHD69J";
		retObj.Extension = "eP s";
		retObj.Photo = new Byte[] { 127, 159, 115, 29, 119, 5, 143, 34, 138, 203, 119, 59, 126, 131, 36, 4, 209, 249, 212, 160, 138, 159, 63, 154, 42, 70, 216, 39, 89, 152, 118, 246, 117, 188, 21, 132, 63, 36, 77, 54, 15, 109, 122, 37, 87, 133, 74, 106, 31, 134, 143, 88, 79, 8, 214, 17, 208, 63, 2, 253, 116, 230, 240, 53, 204, 223, 192, 33, 185, 101, 26, 195, 30, 209, 5, 187, 149, 164, 170, 16, 140, 241, 166, 242, 234, 15, 128, 236, 221, 117, 161, 133, 89, 151, 117, 73, 18, 171, 77, 241 };
		retObj.Notes = "HlQvgmVy5ptvyafnLC2g856f2hsnDuXdYPkkyoFP2o5IjOKBp8EoioXF2362oY01tLq4BtHS2jjxeOs76OICVaTtMXtaSichg2zX";
		retObj.ReportsTo = Convert.ToInt32(1);
		retObj.PhotoPath = "XkUJH3Ih6i mTrQkQ15vpYEanX8LSxFljiY30igbVFRVN90dCA4UvMExPNqHO48hyRYUruqI3BOUEiEBCCltOpVK CK575a3hY VLkyZfJ0DEMs40gKIlCHxE6u3ohyIeIJLFMcdNKEOesV7Qn2dsFGi3cHErBDq92DZmQkn30OCmug7no0eKaEsT2cx8Q5xNTFczvyCNhB554lNFK1Fb7i7kUu OSNF39Q1Ni7Cnumr2AHqeX3NI6OatetPVW1";
		// Foreign key entities
		retObj.FK_Employees_Employees_Ref = GetHydratedStaticNorthwind_dbo_Employees();
		return retObj;
	}
}
