/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class XE_HR_HydratedStaticEntities 
{
	public XE_HR_PACKAGE1_PARAMOUTCURSORS_OM GetHydratedStaticXE_HR_PACKAGE1_PARAMOUTCURSORS_OM(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM();
		// Output parameters
		retObj.CONVERTED_TO_VARCHAR2 = "YoXad0gy br08Cw7Kps yai724HlfGcn8TLANfPCkHWEsEKiGI2FS0Jom9dCHfI0H5Bo7TmvkMBkLvqv0RpkWeL16uopIivDU4wp";
		retObj.Query1_Results!.ToList().Add(new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_Query1());
		retObj.Query2_Results!.ToList().Add(new XE_HR_PACKAGE1_PARAMOUTCURSORS_OM_Query2());
		retObj.Query1_Results!.First()!.EMPLOYEE_ID = Convert.ToDecimal(1);
		retObj.Query1_Results!.First()!.START_DATE = "NoWnmwl";
		retObj.Query1_Results!.First()!.END_DATE = "yUkwf89";
		retObj.Query1_Results!.First()!.JOB_ID = "5Ifv5Zff0l";
		retObj.Query1_Results!.First()!.DEPARTMENT_ID = Convert.ToDecimal(1);
		retObj.Query2_Results!.First()!.DEPARTMENT_ID = Convert.ToDecimal(1);
		retObj.Query2_Results!.First()!.DEPARTMENT_NAME = "vcFhPWyQnV9543hAJ3B6ULsGtY0rAw";
		retObj.Query2_Results!.First()!.MANAGER_ID = Convert.ToDecimal(1);
		retObj.Query2_Results!.First()!.LOCATION_ID = Convert.ToDecimal(1);
		return retObj;
	}
}
