/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202605 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class XE_HR_HydratedStaticEntities 
{
	public XE_HR_EMP_DETAILS_VIEW GetHydratedStaticXE_HR_EMP_DETAILS_VIEW(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_EMP_DETAILS_VIEW();
		retObj.EMPLOYEE_ID = (-822312200);
		retObj.JOB_ID = "1CPlrMXvBp";
		retObj.MANAGER_ID = (665024374);
		retObj.DEPARTMENT_ID = (237445446);
		retObj.LOCATION_ID = (1124577668);
		retObj.COUNTRY_ID = "Ur";
		retObj.FIRST_NAME = "0UXOQ2XCPxlgf97omLgR";
		retObj.LAST_NAME = "dK6G2WaY rI9cLqtDid8Y1Npk";
		retObj.SALARY = (0.4512520822522733M);
		retObj.COMMISSION_PCT = (0.12611078747751514M);
		retObj.DEPARTMENT_NAME = "eHBmkNevibsGpGMI5R0pkQCqAHAr0J";
		retObj.JOB_TITLE = "geacWhl7yHoroAsDI 3EsyHF3fX6g34pdqB";
		retObj.CITY = "kx4GQAnNz3QD8UtTjZycTRJFCvOyfM";
		retObj.STATE_PROVINCE = "PkdzQ15g61Qb76Z1IaZor3LEK";
		retObj.COUNTRY_NAME = "z93AKcDHzyk0HKhaVyXryDNHi46V55wFcGBAOOcg";
		retObj.REGION_NAME = "epEVleh4bXFD4LpED5A602gEy";
		return retObj;
	}
}
