/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_EMP_DETAILS_VIEW(fillPrimaryKey = false) {
	let retObj = new XE_HR_EMP_DETAILS_VIEW_IR();
	retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.JOB_ID = (fillPrimaryKey ? 'HwMF mGxUG' : null);
	retObj.MANAGER_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.DEPARTMENT_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.LOCATION_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.COUNTRY_ID = (fillPrimaryKey ? '1r' : null);
	retObj.FIRST_NAME = 'v YPTjqhmy0AWe3wspRP';
	retObj.LAST_NAME = 'firxNbpiIk7JdO5CgtsI0VHos';
	retObj.SALARY = 0.8295087595097719;
	retObj.COMMISSION_PCT = 0.08347557554371776;
	retObj.DEPARTMENT_NAME = 'n7o3D7GH67vJdxc7uQ 52iBU4a9ejJ';
	retObj.JOB_TITLE = 'dNO44P2squr90w2659rAy2DMEY124dOQzQO';
	retObj.CITY = 'kZqfwq1riNInzYG3iIZTEId8xb1bRi';
	retObj.STATE_PROVINCE = 'LFYkRDvmrcU8uEc7xXhk4pkV6';
	retObj.COUNTRY_NAME = '3k5iyakxhRh2dUvfW04hkt7XkJPa PGMIjLyyZTy';
	retObj.REGION_NAME = 'bh64Q1RFtyer7ZoTqlpYbPD53';
	return retObj;
}
