/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_EMPLOYEES(fillPrimaryKey = false) {
	let retObj = new XE_HR_EMPLOYEES_IR();
	retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.FIRST_NAME = 'ki4TwQlTfu2mpkYhOJbp';
	retObj.LAST_NAME = 'InR4c QydqA b Pz9kiicgffI';
	retObj.EMAIL = '6GA2wwxkMalfrOdKbsgc1C4pI';
	retObj.PHONE_NUMBER = '0V5zjjleZrXFDLSFl2mK';
	retObj.HIRE_DATE = '/Date(10/6/2010 12:00:00 AM)/';
	retObj.JOB_ID = 'qA5FYRN4Ci';
	retObj.SALARY = 0.6589040600502385;
	retObj.COMMISSION_PCT = 0.6819709903629871;
	retObj.MANAGER_ID_IR = encrypt(1);
	retObj.DEPARTMENT_ID_IR = encrypt(1);
	// Foreign key entities
	retObj.EMP_DEPT_FK_Ref_IR = getHydratedStaticXE_HR_DEPARTMENTS_IR();
	retObj.EMP_JOB_FK_Ref_IR = getHydratedStaticXE_HR_JOBS_IR();
	retObj.EMP_MANAGER_FK_Ref_IR = getHydratedStaticXE_HR_EMPLOYEES_IR();
	return retObj;
}
