/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Invoices_IR GetHydratedStaticNorthwind_dbo_Invoices_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Invoices_IR();
		retObj.ShipName = "J nckUMu KLKgN7lo2bbphLeFN5WHFtWot8GlzZL";
		retObj.ShipAddress = "rbDAIFA3F0pu2IujxmUHhtT 0ICgk1sy ND2GNMj9LkPakWYRGzNA2X QyMH";
		retObj.ShipCity = "zppbu o6BCA3MCz";
		retObj.ShipRegion = "qEySL2QI4idhhm7";
		retObj.ShipPostalCode = "fmvg0dZY5B";
		retObj.ShipCountry = "JkPdK0Ok0bHB6JX";
		retObj.CustomerID = (fillPrimaryKey ? "GONSC" : String.Empty);
		retObj.CustomerName = "gXbOR9o3YBefAgDE5vDcHPwI30YYz4txWKjtsL3s";
		retObj.Address = "qgXSL97ckcDJzWg7tc Qn59aCp l73TUOxUTfimRSoZAGuXGxIcX7Sxxc9v8";
		retObj.City = "KWftiirrZDGIUex";
		retObj.Region = "n9T iILk5tXf7e ";
		retObj.PostalCode = "yZP1apQA3t";
		retObj.Country = "b4 GBHFdci1DINI";
		retObj.Salesperson = "X5Ab5H2BWPe7mV2hsV0SsNfd7WX2h6 ";
		retObj.OrderID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.OrderDate = DateTime.Parse("8/28/2001 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("8/17/2008 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("1/19/2002 12:00:00 AM");
		retObj.ShipperName = "6zyGs7jBjS4vOmVWVGIiD629TLU0R7M2yPC0iyPy";
		retObj.ProductID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.ProductName = "vvLxMR8UrCN5FekJCZyNhaP4Gd1iymBQYt8jyhIx";
		retObj.UnitPrice = (0.7913531027911043M);
		retObj.Quantity = (-3295);
		retObj.Discount = (0.27496588F);
		retObj.ExtendedPrice = (0.548773183861212M);
		retObj.Freight = (0.6898343810469904M);
		return retObj;
	}
}
