/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_ProductsAndCategories_OM_IR GetHydratedStaticNorthwind_dbo_ProductsAndCategories_OM_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_ProductsAndCategories_OM_IR();
		retObj.Query1_Results_IR!.ToList().Add(new Northwind_dbo_ProductsAndCategories_OM_Query1_IR());
		retObj.Query1_Results_IR!.First()!.ProductID_IR = _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1));
		retObj.Query1_Results_IR!.First()!.ProductName = "eSTBfmwNkWwHJnlwOStN34IYJVgD6OjClvZyZGZ7";
		retObj.Query1_Results_IR!.First()!.SupplierID_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		retObj.Query1_Results_IR!.First()!.CategoryID_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		retObj.Query1_Results_IR!.First()!.QuantityPerUnit = "esPEp0ZijhzgjlRhIpOZ";
		retObj.Query1_Results_IR!.First()!.UnitPrice = (0.048731072890900284M);
		retObj.Query1_Results_IR!.First()!.UnitsInStock = (-22158);
		retObj.Query1_Results_IR!.First()!.UnitsOnOrder = (8578);
		retObj.Query1_Results_IR!.First()!.ReorderLevel = (24383);
		retObj.Query1_Results_IR!.First()!.Discontinued = (false);
		retObj.Query2_Results_IR!.ToList().Add(new Northwind_dbo_ProductsAndCategories_OM_Query2_IR());
		retObj.Query2_Results_IR!.First()!.CategoryID_IR = _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1));
		retObj.Query2_Results_IR!.First()!.CategoryName = "6GzX0wEWOMDn4ji";
		retObj.Query2_Results_IR!.First()!.Description = "uKwv0ED2HTFwPw1qowGg48BUQqfVyJlYWEUACAmvTbpFYVbisrJOHorHFdnZclDmjj2USODkA LVN6ozDe57WwkFMlEi8DOFVJya";
		retObj.Query2_Results_IR!.First()!.Picture = new Byte[] { 195, 233, 252, 185, 163, 132, 82, 221, 166, 33, 20, 128, 238, 213, 161, 202, 248, 194, 26, 136, 205, 123, 163, 153, 120, 192, 8, 198, 198, 101, 192, 89, 201, 255, 34, 249, 6, 18, 22, 36, 179, 138, 201, 137, 227, 64, 178, 12, 227, 234, 65, 152, 252, 181, 229, 69, 170, 95, 115, 57, 77, 163, 187, 240, 179, 185, 237, 223, 241, 111, 157, 134, 93, 62, 13, 123, 13, 142, 205, 10, 252, 73, 95, 149, 183, 47, 161, 124, 38, 148, 238, 16, 109, 197, 177, 44, 156, 104, 170, 167 };
		return retObj;
	}
}
