/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Categories_IR GetHydratedStaticNorthwind_dbo_Categories_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Categories_IR();
		retObj.CategoryID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CategoryName = "LYz77d1yQjKCZ6w";
		retObj.Description = "Lo45NAjKOWsRLB5aOM4H3bxPnl4Lu4w09sspX15E2Ee5Mo38FPGsI9WxntvLodsMoCKFeaBUIMsbQ nigElFvo9JvdCuTj52XfnB";
		retObj.Picture = new Byte[] { 66, 91, 19, 126, 205, 24, 57, 55, 177, 156, 179, 186, 36, 180, 6, 65, 171, 236, 60, 159, 86, 167, 188, 81, 185, 13, 62, 97, 23, 69, 143, 21, 180, 93, 207, 17, 236, 182, 171, 26, 7, 211, 162, 101, 188, 117, 14, 105, 56, 66, 91, 43, 50, 119, 144, 152, 251, 163, 156, 175, 255, 103, 51, 12, 43, 213, 236, 203, 136, 231, 60, 44, 120, 37, 129, 96, 125, 135, 136, 130, 93, 176, 206, 29, 70, 108, 1, 22, 156, 17, 3, 137, 185, 62, 2, 190, 65, 103, 232, 83 };
		return retObj;
	}
}
