/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Customers_IR GetHydratedStaticNorthwind_dbo_Customers_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Customers_IR();
		retObj.CustomerID = (fillPrimaryKey ? "UaDDv" : String.Empty);
		retObj.CompanyName = "hTgzU9of9XAIA39IrwQefv4kLeKVDTUDgxNQa2df";
		retObj.ContactName = "XKtmWiyFQNBpKLcBWyTqfnm06cHKRz";
		retObj.ContactTitle = "OwfOWbq8Pyk7rfrmTQTDCnmCd6AEWr";
		retObj.Address = "TyIs6CrNqgTu 2nSmos1nfVfp9UthYCMAgtgA6PnmzwLrdYppfxvYDvvKs90";
		retObj.City = "yU8SUiPBMQbsZ75";
		retObj.Region = "pt39glDKoPtFfFg";
		retObj.PostalCode = "O7AijW9rrC";
		retObj.Country = "DF0MjJP0oPvRnHX";
		retObj.Phone = "RsFjxXz8dwe6Qy9DVBtuWmO8";
		retObj.Fax = "mUMnfMSshJEidBl1ZMyJ7PZF";
		return retObj;
	}
}
