/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Orders_Qry_IR GetHydratedStaticNorthwind_dbo_Orders_Qry_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders_Qry_IR();
		retObj.OrderID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CustomerID = (fillPrimaryKey ? "ATTOR" : String.Empty);
		retObj.EmployeeID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.OrderDate = DateTime.Parse("9/4/2021 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("1/21/2020 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("11/20/2000 12:00:00 AM");
		retObj.ShipVia = (1500282709);
		retObj.Freight = (0.12009338236307665M);
		retObj.ShipName = "nIGl529 Af62Grq1B6mI1LlU21wT9LPcZmQ0b6By";
		retObj.ShipAddress = "TRt3budKrgUrw24xlzD3CGsN3oSbnsFetR8YDPqceIf6OM3e4H5w57t2fqDj";
		retObj.ShipCity = "aEGbFofPteaeZVO";
		retObj.ShipRegion = "aI5EmVc1ZLZgq48";
		retObj.ShipPostalCode = "wM44F9hpRr";
		retObj.ShipCountry = "R tg54c2Q68Bs1i";
		retObj.CompanyName = "D4yNOylHr7dJIHgaEuUTG8VN4T6W5ksvKEodF8x7";
		retObj.Address = "ZDoELNh8zpGDNFyWSUt5CbdhQVtxrzdCUMjvivMi j6KJOmASeEmAaeOYpwG";
		retObj.City = "oW oO2x9i4OIB7u";
		retObj.Region = "50QuY4FeN R8aWz";
		retObj.PostalCode = "PChlnagcG5";
		retObj.Country = "CUiRtuXIHaN6JJ ";
		return retObj;
	}
}
