/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195906 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Suppliers_IR GetHydratedStaticNorthwind_dbo_Suppliers_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Suppliers_IR();
		retObj.SupplierID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CompanyName = "CzUE0OAwjZ7zNbADdb9SH57LbE1pGxgbzOGuCuk3";
		retObj.ContactName = "99 cvNKFyc0hJpP8FNJbb2cCXkczkV";
		retObj.ContactTitle = "Oxbe6ZRDeK  YmOmVUnHBfjM lOI2u";
		retObj.Address = "dGX4oIkB7eJLBbFwuw3D0hF4Gsq0Q2Zo9nMC32CZdvDc3g8ljBN9mOIXkjgf";
		retObj.City = " zVomG7z7KPD2ms";
		retObj.Region = "jxZDKYwyWKFBSIL";
		retObj.PostalCode = "dypZxxrfGs";
		retObj.Country = "f w65MhUhA4mM57";
		retObj.Phone = "L7dDbLW7SqhGRQypAoVatnOV";
		retObj.Fax = "PYegh EnqClSh48MOK7R8ikA";
		retObj.HomePage = "rkKA1D08lFjofZF4HfaJ2BepWncWTaDwr7o4nnEEESjFfF1HuCyIoAZVvOIhlFAhqEVoHrfS43MmHuGJtOtqn5Bhl5ynOMmqd7zg";
		return retObj;
	}
}
