/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class XE_HR_HydratedStaticIndirectReferenceTransformerModels : XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public XE_HR_EMPLOYEES_IR GetHydratedStaticXE_HR_EMPLOYEES_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_EMPLOYEES_IR();
		retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.FIRST_NAME = "dY91jN4PTPQCoCY2SlJK";
		retObj.LAST_NAME = "AxstWZgI9IJwbZorYMi5sbAWc";
		retObj.EMAIL = "fgZFTVeU25ugmVkmH4qvb2FWK";
		retObj.PHONE_NUMBER = "p0xoterqtpLFF5 tp7QQ";
		retObj.HIRE_DATE = DateTime.Parse("10/27/2018 12:00:00 AM");
		retObj.JOB_ID = "iGHiSYZ2nO";
		retObj.SALARY = (0.4659136247245135M);
		retObj.COMMISSION_PCT = (0.036619622628961235M);
		retObj.MANAGER_ID_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		retObj.DEPARTMENT_ID_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		// Foreign key entities
		retObj.EMP_DEPT_FK_Ref_IR = GetHydratedStaticXE_HR_DEPARTMENTS_IR();
		retObj.EMP_JOB_FK_Ref_IR = GetHydratedStaticXE_HR_JOBS_IR();
		retObj.EMP_MANAGER_FK_Ref_IR = GetHydratedStaticXE_HR_EMPLOYEES_IR();
		return retObj;
	}
}
