/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class XE_HR_HydratedStaticIndirectReferenceTransformerModels : XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public XE_HR_EMP_DETAILS_VIEW_IR GetHydratedStaticXE_HR_EMP_DETAILS_VIEW_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_EMP_DETAILS_VIEW_IR();
		retObj.EMPLOYEE_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.JOB_ID = (fillPrimaryKey ? "zbZnVG8PGH" : String.Empty);
		retObj.MANAGER_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.DEPARTMENT_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.LOCATION_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.COUNTRY_ID = (fillPrimaryKey ? "nt" : String.Empty);
		retObj.FIRST_NAME = "mkNgJOkU2JpiwiGKIZUm";
		retObj.LAST_NAME = "gfWa1tIvtWQvAjnnEUWI7wxcy";
		retObj.SALARY = (0.3868535374579749M);
		retObj.COMMISSION_PCT = (0.6984421246614955M);
		retObj.DEPARTMENT_NAME = "Y3te4dg4d7swm99YyJ0ZiRTKb9NLXH";
		retObj.JOB_TITLE = "qxhtx FRrNr7al1SHnHqPGgcpPTi89EmrGJ";
		retObj.CITY = "VLMAn5UVCHL EJ0z5ouOWvR8ejzGYs";
		retObj.STATE_PROVINCE = "mlooRZUqOxuKYeBURzuRgjZXk";
		retObj.COUNTRY_NAME = "3Szt6D426cHMv PEm  ZA1WxDD80LQzl5F wXior";
		retObj.REGION_NAME = "OD1qxCfBXGuuyjQmfCFdnAT8F";
		return retObj;
	}
}
