/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Orders_Qry_IR GetHydratedStaticNorthwind_dbo_Orders_Qry_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders_Qry_IR();
		retObj.OrderID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CustomerID = (fillPrimaryKey ? "gj9CY" : String.Empty);
		retObj.EmployeeID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.OrderDate = DateTime.Parse("2/19/2023 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("8/11/2020 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("1/6/2000 12:00:00 AM");
		retObj.ShipVia = (-904910388);
		retObj.Freight = (0.6639643512172305M);
		retObj.ShipName = "xmuEMO5BFCeSzh5XwCDUuOJk4gwE1TTAoEytJxCb";
		retObj.ShipAddress = "JCgSFpeyIruyZWT6GQkcdjiBL5v1tbu64CktZPG09ocS4UGWzyViV Yg9M G";
		retObj.ShipCity = "kVZH7wZBEeo1mBf";
		retObj.ShipRegion = "Mr5dcih3vUhPctF";
		retObj.ShipPostalCode = "kG1UTtP32g";
		retObj.ShipCountry = "VEKixL6Fe7vXUzr";
		retObj.CompanyName = "Uaw3e7iSjClCiH7MBzcvt1miFQJOhrzpfvNMoIRs";
		retObj.Address = "Rhw61aMWIB9c6DNhdAnh8Y8UwRH EWbSiEswspr0k8lML8VKIbp1qCIASKBv";
		retObj.City = "DjY1tNpq9nPWr72";
		retObj.Region = "Ji1A5csjIcIEyHm";
		retObj.PostalCode = "RA8ch8dmyr";
		retObj.Country = "aDipy0gfyTCy6gX";
		return retObj;
	}
}
