/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Categories_IR GetHydratedStaticNorthwind_dbo_Categories_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Categories_IR();
		retObj.CategoryID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CategoryName = "DmShxA0DwOvbwYh";
		retObj.Description = "ILVmKBGQuHAVZ8QjPANym3VUFW wYCm5mkW4cfQ9VjL7i9Opfxc4VDBgs4ko3ZhyR0c7CUp2MPU2dBPbjLrBhoQx1F 8BUqO47r7";
		retObj.Picture = new Byte[] { 26, 127, 89, 251, 24, 202, 117, 71, 90, 65, 155, 71, 17, 43, 171, 221, 71, 246, 151, 54, 169, 6, 241, 230, 151, 27, 135, 53, 150, 218, 90, 15, 130, 207, 1, 12, 119, 221, 86, 49, 208, 19, 37, 12, 179, 209, 115, 5, 60, 245, 209, 7, 115, 45, 98, 154, 14, 206, 102, 69, 204, 18, 12, 74, 87, 203, 206, 2, 56, 10, 152, 199, 26, 116, 47, 213, 201, 122, 42, 146, 124, 68, 206, 174, 138, 7, 12, 165, 208, 247, 194, 103, 97, 87, 254, 236, 85, 132, 38, 134 };
		return retObj;
	}
}
