/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Invoices_IR GetHydratedStaticNorthwind_dbo_Invoices_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Invoices_IR();
		retObj.ShipName = "GDBBAxQfR9HZcqlq3IJinu6ac3nwNDDUCIr2UkdX";
		retObj.ShipAddress = "wvDuesst56bBzUVW3rDuAY r41drF4Tr7aMlPjYOMniUvjiw0hf9USxPzKQ6";
		retObj.ShipCity = "8cj2UqaVMOuLnhY";
		retObj.ShipRegion = "CBH5EZaZtpJyWRE";
		retObj.ShipPostalCode = "sqh8rWJsl5";
		retObj.ShipCountry = "bli41fop7hOgVDF";
		retObj.CustomerID = (fillPrimaryKey ? "7ZekC" : String.Empty);
		retObj.CustomerName = "sOsZsdVLxlLtAVHL7sypiDK9itaBxy0sIVcizTSi";
		retObj.Address = "WGbFcMLpPMlxk1g055z8iHPLsQ2BS8GIhL7w5bIe6wtJYIofuncc qRMBCSh";
		retObj.City = "EON3zqLPfIyu5os";
		retObj.Region = "r Auj41HuwhW7et";
		retObj.PostalCode = "yY1jWDs0iK";
		retObj.Country = "MeajccqwsMG29S9";
		retObj.Salesperson = "utYYjJlG5b h qUmekheUfADxEzhO0 ";
		retObj.OrderID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.OrderDate = DateTime.Parse("2/27/1999 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("3/11/1998 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("9/7/2022 12:00:00 AM");
		retObj.ShipperName = "pktxQ4akRicAIb4y2usRuJjLABrA9oDMX7dtlFjS";
		retObj.ProductID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.ProductName = "8FfCzhqb9qCzbr1HdNvDAr6ioaQ0YCVRVny9ZOxx";
		retObj.UnitPrice = (0.5499603074681354M);
		retObj.Quantity = (-15436);
		retObj.Discount = (0.615808F);
		retObj.ExtendedPrice = (0.18775606478118811M);
		retObj.Freight = (0.4280507280286717M);
		return retObj;
	}
}
