/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Employees_IR GetHydratedStaticNorthwind_dbo_Employees_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Employees_IR();
		retObj.EmployeeID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.LastName = "uP8cOtMv0VFOze94qvJ4";
		retObj.FirstName = "IIhJmmWoms";
		retObj.Title = "x3u6DybmZ8vhxK5Wgxczqdv3V4 3KW";
		retObj.TitleOfCourtesy = "poVTV8yWXF1tk0qjGQz4VOXSE";
		retObj.BirthDate = DateTime.Parse("12/14/1997 12:00:00 AM");
		retObj.HireDate = DateTime.Parse("11/23/2015 12:00:00 AM");
		retObj.Address = "ryvN21v4trFe1ftuUM6SSYFYOCXSHnfDHTs9yQ5SdWw8K2WK79CEueMd37JC";
		retObj.City = "eSGRgG 5nWRY9ey";
		retObj.Region = "wx0jxsdrtmVv544";
		retObj.PostalCode = "TclEh1tjM2";
		retObj.Country = "lW7BPgX7UhDxNxH";
		retObj.HomePhone = "5LNCBtfycBEhVqrOGnuC04nE";
		retObj.Extension = "aIoa";
		retObj.Photo = new Byte[] { 227, 167, 50, 221, 122, 68, 25, 109, 234, 11, 46, 96, 84, 17, 189, 125, 67, 169, 39, 34, 21, 217, 79, 234, 208, 204, 152, 59, 42, 137, 4, 98, 229, 44, 164, 148, 74, 160, 4, 185, 48, 5, 72, 160, 228, 17, 216, 62, 185, 195, 88, 9, 49, 136, 138, 2, 185, 98, 137, 79, 163, 93, 116, 102, 161, 88, 62, 119, 219, 11, 207, 7, 119, 60, 182, 112, 106, 214, 188, 184, 245, 11, 194, 146, 82, 48, 191, 79, 212, 36, 114, 57, 234, 227, 47, 61, 134, 21, 8, 105 };
		retObj.Notes = "X05aimmAWV2bItNPbHGYB9ruGCNHMlkZJ 3pIfhUB8ak19gUSdX39xYfWZmCjuviAlybjKGCw3MxqXpcZnjw2ws2eRTda3WqNYfg";
		retObj.ReportsTo_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		retObj.PhotoPath = "7wcdRjFiY6HaOwQ9DxuJyw5GK410C9elV85HW6fpWy8XvYgJP9rLT0mliPAcHdhpRYM7V52iSU9idWwN1sCG2wGg8n8cOmHKzvLOqeZcv3XKlVwcMbXOeCI4uQYl4Sa 4wsJN6cFHbxzJkCvMwDBuS4G4OQxgVyWK4sDJ6T342G5DOHmWS7hXP5M10iQxEB9MVS3ah9ebpR0FEWiDJItdIQMcj6NV8mI0crvFrslY4zVc1JkAz Y3GOt5K3uC w";
		// Foreign key entities
		retObj.FK_Employees_Employees_Ref_IR = GetHydratedStaticNorthwind_dbo_Employees_IR();
		return retObj;
	}
}
