/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Suppliers_IR GetHydratedStaticNorthwind_dbo_Suppliers_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Suppliers_IR();
		retObj.SupplierID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CompanyName = "9g98RCY20Eae dS4VFYgIwJwggXEvswWAjR6m4hW";
		retObj.ContactName = "mfzLZjhDoB sbdB23xVcBkWLt7SWcU";
		retObj.ContactTitle = "5zJuRj7JisVyFfMO88sLnU2RZ2V8Pp";
		retObj.Address = "8kqhertXj5xPs0gmsuyTvppOxNryjBYiHejqtshzBEub95lnvmdPp87mD4U8";
		retObj.City = "LByqNr2k sk92wR";
		retObj.Region = "t3gX8VJqMpiY7Y1";
		retObj.PostalCode = "sSFrzFHQs8";
		retObj.Country = "AofNmMvJZQaV7Cq";
		retObj.Phone = "yiyEnc8sgy13pViZEntwd5Tc";
		retObj.Fax = "9tzq5OqDKukQBu4y1qjPZjU9";
		retObj.HomePage = "foKLM6TUcrbJ Q9T2FNOdnPpQT3oxpr2NnP0GbcUgJaZMlZmPteUkDp9RE5WX7gHlMJXvF5S8GkbQCbusqZVFPLy9AlGigXZHQRx";
		return retObj;
	}
}
