/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307195803 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Customers_IR GetHydratedStaticNorthwind_dbo_Customers_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Customers_IR();
		retObj.CustomerID = (fillPrimaryKey ? "4M72D" : String.Empty);
		retObj.CompanyName = "MzKqGTfG4Y5j8zQEaZb5p5otNUCKeSPbOpKdQol7";
		retObj.ContactName = "0Q TJRAfJZ0hyaDUzUrNoELtc0SOOX";
		retObj.ContactTitle = "s6jE rXIbp1FkispUMIMbjXu4zU9HR";
		retObj.Address = "EwR9H6vJxGXUhxocIQiu2CqIDKyvk4Mb7UnFBdmB7ZU6HnUOHI5Efb5RHb4a";
		retObj.City = "Lprk46XaEUbneNo";
		retObj.Region = "MIJ3qF3b1 8eV1Z";
		retObj.PostalCode = "WFRVDkOI2R";
		retObj.Country = "IEdLalVT1SIR9bo";
		retObj.Phone = "8bkti2UnlvTcM0lOqyeCs4 I";
		retObj.Fax = "UMRC0ZMBQpRde2GfAez6t94t";
		return retObj;
	}
}
