/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class XE_HR_HydratedStaticEntities 
{
	public XE_HR_EMP_DETAILS_VIEW GetHydratedStaticXE_HR_EMP_DETAILS_VIEW(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_EMP_DETAILS_VIEW();
		retObj.EMPLOYEE_ID = (-1692511726);
		retObj.JOB_ID = "ox5UsNs012";
		retObj.MANAGER_ID = (1028713315);
		retObj.DEPARTMENT_ID = (1296791740);
		retObj.LOCATION_ID = (1999659800);
		retObj.COUNTRY_ID = "vz";
		retObj.FIRST_NAME = "ez7zLw810D4M2qyHOFDP";
		retObj.LAST_NAME = "NI5kXNR282Y6ShLStpZJBNRpU";
		retObj.SALARY = (0.7191360659303173M);
		retObj.COMMISSION_PCT = (0.8462120361014532M);
		retObj.DEPARTMENT_NAME = "i7TmWXb5rXOlNVmfWmHyVmfQeC8coo";
		retObj.JOB_TITLE = "EbIbCro8r24AgWE2N Me6NZOpPIMlyndAjP";
		retObj.CITY = "sFRIBN1lv9ldGlM89FxEeIkOzMd9na";
		retObj.STATE_PROVINCE = "At4uOf7XJTyP3u6qnTvNSUh7M";
		retObj.COUNTRY_NAME = "aQbNAvXLt6xH6RXgPLX5sItG2sHfLtPDMoLYHYZc";
		retObj.REGION_NAME = "M5V6UAwgNCADIVCByYrLIKeWq";
		return retObj;
	}
}
