/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class XE_HR_HydratedStaticEntities 
{
	public XE_HR_LOCATIONS GetHydratedStaticXE_HR_LOCATIONS(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_LOCATIONS();
		retObj.LOCATION_ID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.STREET_ADDRESS = "qXT5NLdGNjYd3JdFWq96qHiVqjr8 8b1 veajogj";
		retObj.POSTAL_CODE = "h0j72m2GO2oV";
		retObj.CITY = "YHAV0CFBkbeHg3HKqxkU1azp 2SHxN";
		retObj.STATE_PROVINCE = "pZpZVaLb0FoBhKSKUeJ0s0ida";
		retObj.COUNTRY_ID = "pK";
		// Foreign key entities
		retObj.LOC_C_ID_FK_Ref = GetHydratedStaticXE_HR_COUNTRIES();
		return retObj;
	}
}
