/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202507 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class XE_HR_HydratedStaticEntities 
{
	public XE_HR_EMPLOYEES GetHydratedStaticXE_HR_EMPLOYEES(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_EMPLOYEES();
		retObj.EMPLOYEE_ID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.FIRST_NAME = "jMKCTVs2v2dIAMvijLvd";
		retObj.LAST_NAME = "edwYQaqr0AhqfzISnQaNFkYj0";
		retObj.EMAIL = "gZbj0FPcpCRaWiP1xHdadcLQk";
		retObj.PHONE_NUMBER = "akq2IYEJpspPJePFkN H";
		retObj.HIRE_DATE = DateTime.Parse("5/2/2015 12:00:00 AM");
		retObj.JOB_ID = "JQvxIlP0BW";
		retObj.SALARY = (0.6654848212281124M);
		retObj.COMMISSION_PCT = (0.5246275654681773M);
		retObj.MANAGER_ID = Convert.ToInt32(1);
		retObj.DEPARTMENT_ID = Convert.ToInt32(1);
		// Foreign key entities
		retObj.EMP_DEPT_FK_Ref = GetHydratedStaticXE_HR_DEPARTMENTS();
		retObj.EMP_JOB_FK_Ref = GetHydratedStaticXE_HR_JOBS();
		retObj.EMP_MANAGER_FK_Ref = GetHydratedStaticXE_HR_EMPLOYEES();
		return retObj;
	}
}
